// Auto-generated by patch_client_livekit.py — LiveKit SDK edition
#ifndef VIDMA_JS_H
#define VIDMA_JS_H

constexpr const char* VIDMA_JS = R"js(
// =====================================================================
// Vidma client — LiveKit SDK edition (Sprint 2)
// =====================================================================
'use strict';

const { Room, RoomEvent, Track, ConnectionState, DisconnectReason } = LivekitClient;

let room = null;
let currentRoomId = null;
let currentName = null;
let currentSessionId = null;   // server-issued identity
let selectedRating = 0;

// map: participantIdentity -> { wrapperEl, videoEl, stream }
const remotePanels = new Map();

// ---------------------------------------------------------------------
// util
// ---------------------------------------------------------------------
function showToast(text) {
    const t = document.getElementById('toast');
    if (!t) return;
    t.textContent = text;
    t.classList.add('show');
    setTimeout(() => t.classList.remove('show'), 2000);
}

function setSecurityBar(visible) {
    const b = document.getElementById('security-bar');
    if (b) b.style.display = visible ? 'flex' : 'none';
}

function setLocalVideoLabel(txt) {
    const el = document.getElementById('local-video-label');
    if (el) el.textContent = txt;
}

// ---------------------------------------------------------------------
// room creation / joining
// ---------------------------------------------------------------------
async function createRoom() {
    let name = (document.getElementById('create-name')?.value || '').trim() || 'Гость';
    try {
        const res = await fetch('/api/room/create', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ name })
        });
        const data = await res.json();
        if (!data.success) { showToast('Не удалось создать комнату'); return; }
        currentRoomId = data.roomId;
        currentName = name;
        document.getElementById('created-room-id').textContent = data.roomId;
        document.getElementById('room-created').style.display = 'block';
    } catch (e) {
        showToast('Ошибка соединения');
        console.error(e);
    }
}

function copyRoomLink() {
    if (!currentRoomId) return;
    const link = location.origin + '/?room=' + currentRoomId;
    const text = link + '\nVidma — Видеовстречи в один клик';
    navigator.clipboard.writeText(text).then(() => showToast('Ссылка скопирована'));
}

function joinCreatedRoom() {
    if (currentRoomId && currentName) joinRoomById(currentRoomId, currentName);
}

async function joinRoom() {
    let name = (document.getElementById('join-name')?.value || '').trim() || 'Гость';
    let raw = (document.getElementById('room-id')?.value || '').trim();
    const digits = raw.replace(/\D/g, '');
    if (digits.length !== 9) { alert('Введите 9 цифр кода комнаты'); return; }
    const roomId = digits.slice(0,3) + '-' + digits.slice(3,6) + '-' + digits.slice(6,9);
    try {
        const res = await fetch('/api/room/' + roomId + '/exists');
        const data = await res.json();
        if (!data.exists) { alert('Комната не найдена'); return; }
        joinRoomById(roomId, name);
    } catch (e) { alert('Ошибка соединения'); }
}

async function joinRoomById(roomId, name) {
    currentRoomId = roomId;
    currentName = name;
    await showLobby(roomId, name);
}

// =====================================================================
// Lobby — preview, device picker, audio level, separate permissions
// =====================================================================
const lobbyState = {
    stream: null,
    audioCtx: null,
    analyser: null,
    levelRaf: null,
    micEnabled: true,
    camEnabled: true,
};

function showLobby(roomId, name) {
    currentRoomId = roomId;
    currentName = name;
    document.getElementById('main-screen').style.display = 'none';
    document.getElementById('call-screen').style.display = 'none';
    document.getElementById('lobby-screen').classList.add('active');
    return startLobbyPreview();
}

async function startLobbyPreview() {
    try {
        const stream = await navigator.mediaDevices.getUserMedia({
            video: { width: { ideal: 1280 }, height: { ideal: 720 } },
            audio: { echoCancellation: true, noiseSuppression: true, autoGainControl: true }
        });
        lobbyState.stream = stream;
        lobbyState.micEnabled = true;
        lobbyState.camEnabled = true;

        const vid = document.getElementById('lobby-video');
        vid.srcObject = stream;
        document.getElementById('lobby-preview-box').classList.remove('no-video');
        const micOn = document.getElementById('lobby-mic-svg-on');
        const micOff = document.getElementById('lobby-mic-svg-off');
        const camOn = document.getElementById('lobby-cam-svg-on');
        const camOff = document.getElementById('lobby-cam-svg-off');
        if (micOn) micOn.style.display = '';
        if (micOff) micOff.style.display = 'none';
        if (camOn) camOn.style.display = '';
        if (camOff) camOff.style.display = 'none';
        document.getElementById('lobby-mic-toggle').classList.add('on');
        document.getElementById('lobby-mic-toggle').classList.remove('off');
        document.getElementById('lobby-cam-toggle').classList.add('on');
        document.getElementById('lobby-cam-toggle').classList.remove('off');

        await populateLobbyDevices();
        startAudioLevelMeter();
    } catch (err) {
        console.warn('Lobby: getUserMedia failed', err);
        // Если пользователь отказал — просто показываем модалку выбора
        const modal = document.getElementById('camera-choice-modal');
        if (modal) modal.classList.add('active');
    }
}

async function populateLobbyDevices() {
    try {
        const devices = await navigator.mediaDevices.enumerateDevices();
        const micSel = document.getElementById('lobby-mic-select');
        const camSel = document.getElementById('lobby-cam-select');
        const currentMic = lobbyState.stream ? (lobbyState.stream.getAudioTracks()[0]?.getSettings().deviceId) : null;
        const currentCam = lobbyState.stream ? (lobbyState.stream.getVideoTracks()[0]?.getSettings().deviceId) : null;

        micSel.innerHTML = '';
        camSel.innerHTML = '';

        let micCount = 0, camCount = 0;
        devices.forEach(d => {
            if (d.kind === 'audioinput') {
                micCount++;
                const opt = document.createElement('option');
                opt.value = d.deviceId;
                opt.textContent = d.label || ('Микрофон ' + micCount);
                if (currentMic && d.deviceId === currentMic) opt.selected = true;
                micSel.appendChild(opt);
            } else if (d.kind === 'videoinput') {
                camCount++;
                const opt = document.createElement('option');
                opt.value = d.deviceId;
                opt.textContent = d.label || ('Камера ' + camCount);
                if (currentCam && d.deviceId === currentCam) opt.selected = true;
                camSel.appendChild(opt);
            }
        });

        micSel.onchange = () => switchLobbyDevice('audio', micSel.value);
        camSel.onchange = () => switchLobbyDevice('video', camSel.value);
    } catch (e) {
        console.warn('enumerateDevices failed', e);
    }
}

async function switchLobbyDevice(kind, deviceId) {
    if (!lobbyState.stream || !deviceId) return;
    try {
        const newStream = await navigator.mediaDevices.getUserMedia({
            [kind]: { deviceId: { exact: deviceId } }
        });
        const newTrack = newStream.getTracks()[0];
        // Убираем старые треки того же типа
        lobbyState.stream.getTracks()
            .filter(t => t.kind === kind)
            .forEach(t => { lobbyState.stream.removeTrack(t); t.stop(); });
        lobbyState.stream.addTrack(newTrack);

        if (kind === 'video') {
            document.getElementById('lobby-video').srcObject = lobbyState.stream;
        } else {
            startAudioLevelMeter();
        }
    } catch (e) {
        console.warn('switchLobbyDevice failed', e);
    }
}

function startAudioLevelMeter() {
    if (!lobbyState.stream) return;
    stopAudioLevelMeter();
    const audioTracks = lobbyState.stream.getAudioTracks();
    if (audioTracks.length === 0) return;

    try {
        const ctx = new (window.AudioContext || window.webkitAudioContext)();
        lobbyState.audioCtx = ctx;
        const src = ctx.createMediaStreamSource(new MediaStream(audioTracks));
        const analyser = ctx.createAnalyser();
        analyser.fftSize = 512;
        src.connect(analyser);
        lobbyState.analyser = analyser;

        const data = new Uint8Array(analyser.frequencyBinCount);
        const bar = document.getElementById('lobby-level-bar');

        const tick = () => {
            if (!lobbyState.analyser) return;
            analyser.getByteFrequencyData(data);
            let sum = 0;
            for (let i = 0; i < data.length; i++) sum += data[i];
            const avg = sum / data.length;
            const pct = Math.min(100, (avg / 128) * 100 * 2.2);
            bar.style.width = pct + '%';
            lobbyState.levelRaf = requestAnimationFrame(tick);
        };
        tick();
    } catch (e) {
        console.warn('audio meter failed', e);
    }
}

function stopAudioLevelMeter() {
    if (lobbyState.levelRaf) {
        cancelAnimationFrame(lobbyState.levelRaf);
        lobbyState.levelRaf = null;
    }
    if (lobbyState.audioCtx) {
        try { lobbyState.audioCtx.close(); } catch (e) {}
        lobbyState.audioCtx = null;
    }
    lobbyState.analyser = null;
    const bar = document.getElementById('lobby-level-bar');
    if (bar) bar.style.width = '0%';
}

function lobbyToggleMic() {
    if (!lobbyState.stream) return;
    lobbyState.micEnabled = !lobbyState.micEnabled;
    lobbyState.stream.getAudioTracks().forEach(t => t.enabled = lobbyState.micEnabled);
    const btn = document.getElementById('lobby-mic-toggle');
    const on = document.getElementById('lobby-mic-svg-on');
    const off = document.getElementById('lobby-mic-svg-off');
    if (on) on.style.display = lobbyState.micEnabled ? '' : 'none';
    if (off) off.style.display = lobbyState.micEnabled ? 'none' : '';
    btn.classList.toggle('on', lobbyState.micEnabled);
    btn.classList.toggle('off', !lobbyState.micEnabled);
}

function lobbyToggleCam() {
    if (!lobbyState.stream) return;
    lobbyState.camEnabled = !lobbyState.camEnabled;
    lobbyState.stream.getVideoTracks().forEach(t => t.enabled = lobbyState.camEnabled);
    const btn = document.getElementById('lobby-cam-toggle');
    const on = document.getElementById('lobby-cam-svg-on');
    const off = document.getElementById('lobby-cam-svg-off');
    if (on) on.style.display = lobbyState.camEnabled ? '' : 'none';
    if (off) off.style.display = lobbyState.camEnabled ? 'none' : '';
    btn.classList.toggle('on', lobbyState.camEnabled);
    btn.classList.toggle('off', !lobbyState.camEnabled);
    document.getElementById('lobby-preview-box').classList.toggle('no-video', !lobbyState.camEnabled);
}

function cancelLobby() {
    stopAudioLevelMeter();
    if (lobbyState.stream) {
        lobbyState.stream.getTracks().forEach(t => t.stop());
        lobbyState.stream = null;
    }
    document.getElementById('lobby-screen').classList.remove('active');
    document.getElementById('main-screen').style.display = 'block';
    document.getElementById('lobby-video').srcObject = null;
}

async function confirmLobbyEntry() {
    stopAudioLevelMeter();
    // Важно: сохраняем состояние ПЕРЕД скрытием лобби
    const stream = lobbyState.stream;
    // Убеждаемся что треки физически в нужном состоянии
    if (stream) {
        stream.getVideoTracks().forEach(t => t.enabled = lobbyState.camEnabled);
        stream.getAudioTracks().forEach(t => t.enabled = lobbyState.micEnabled);
    }
    document.getElementById('lobby-screen').classList.remove('active');
    document.getElementById('call-screen').style.display = 'block';
    document.getElementById('current-room-code').textContent = currentRoomId;
    setLocalVideoLabel(currentName + ' (Вы)');
    await connectToRoom(stream);
}

// =====================================================================
// Real connection (uses already-obtained stream from lobby)
// =====================================================================
async function connectToRoom(preStream) {
    // 1. Get token from server
    let data;
    try {
        const res = await fetch('/api/room/' + currentRoomId + '/token', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ name: currentName })
        });
        data = await res.json();
        if (!data.livekitUrl || !data.livekitToken) {
            throw new Error('Server did not return livekit config');
        }
    } catch (e) {
        alert('Не удалось получить токен: ' + e.message);
        leaveCall();
        return;
    }
    currentSessionId = data.identity;

    // 2. Create room
    room = new Room({
        adaptiveStream: false,
        dynacast: true,
        videoCaptureDefaults: {
            resolution: { width: 1920, height: 1080, frameRate: 30 }
        },
        audioCaptureDefaults: {
            echoCancellation: true,
            noiseSuppression: true,
            autoGainControl: true,
            sampleRate: 48000,
            channelCount: 1
        },
        publishDefaults: {
            simulcast: true,
            videoSimulcastLayers: undefined,
            videoCodec: 'vp8',
            dtx: true,
            red: true
        }
    });

    // 3. Event handlers
    room
        .on(RoomEvent.Connected, onConnected)
        .on(RoomEvent.Disconnected, onDisconnected)
        .on(RoomEvent.ParticipantConnected, onParticipantConnected)
        .on(RoomEvent.ParticipantDisconnected, onParticipantDisconnected)
        .on(RoomEvent.TrackSubscribed, onTrackSubscribed)
        .on(RoomEvent.TrackUnsubscribed, onTrackUnsubscribed)
        .on(RoomEvent.LocalTrackPublished, onLocalTrackPublished)
        .on(RoomEvent.DataReceived, onDataReceived);

    // 4. Connect
    try {
        await room.connect(data.livekitUrl, data.livekitToken);
    } catch (e) {
        alert('Не удалось подключиться к комнате: ' + e.message);
        leaveCall();
        return;
    }

    setSecurityBar(true);

    // 5. Publish tracks we already obtained in lobby
    if (preStream) {
        for (const track of preStream.getVideoTracks()) {
            try {
                const wantEnabled = lobbyState.camEnabled;
                track.enabled = wantEnabled;
                await room.localParticipant.publishTrack(track, {
                    source: Track.Source.Camera,
                    simulcast: true,
                    videoEncoding: {
                        maxBitrate: 3_000_000,
                        maxFramerate: 30
                    },
                    degradationPreference: 'maintain-resolution'
                });
                track.enabled = wantEnabled;
            } catch (e) { console.warn('publish video failed', e); }
        }
        for (const track of preStream.getAudioTracks()) {
            try {
                const wantEnabled = lobbyState.micEnabled;
                track.enabled = wantEnabled;
                await room.localParticipant.publishTrack(track, {
                    source: Track.Source.Microphone,
                    dtx: true,
                    red: true
                });
                track.enabled = wantEnabled;
            } catch (e) { console.warn('publish audio failed', e); }
        }

        // Двойная страховка через LiveKit API
        try {
            if (!lobbyState.camEnabled) {
                await room.localParticipant.setCameraEnabled(false);
            }
            if (!lobbyState.micEnabled) {
                await room.localParticipant.setMicrophoneEnabled(false);
            }
        } catch (e) { console.warn('state sync failed', e); }

        // Обновить кнопки в главном окне звонка
        const camOn = document.getElementById('cam-icon-on');
        const camOff = document.getElementById('cam-icon-off');
        const micOn = document.getElementById('mic-icon-on');
        const micOff = document.getElementById('mic-icon-off');
        if (camOn && camOff) {
            camOn.style.display = lobbyState.camEnabled ? '' : 'none';
            camOff.style.display = lobbyState.camEnabled ? 'none' : '';
        }
        if (micOn && micOff) {
            micOn.style.display = lobbyState.micEnabled ? '' : 'none';
            micOff.style.display = lobbyState.micEnabled ? 'none' : '';
        }
    }

    // 6. Attach local video
    const camPub = room.localParticipant.getTrackPublication(Track.Source.Camera);
    if (camPub && camPub.videoTrack) {
        camPub.videoTrack.attach(document.getElementById('local-video'));
    }

    // 7. Attach already-present remote participants
    room.remoteParticipants.forEach(p => attachParticipant(p));
}

// ---------------------------------------------------------------------
// room event handlers
// ---------------------------------------------------------------------
function onConnected() {
    console.log('LiveKit: connected as', room.localParticipant.identity);
}

function onDisconnected(reason) {
    console.log('LiveKit: disconnected, reason =', reason);
    leaveCallUI();
    if (reason === DisconnectReason.CLIENT_INITIATED) {
        showRatingModal();
    } else {
        showToast('Соединение с комнатой потеряно');
    }
}

function onParticipantConnected(participant) {
    console.log('Participant joined:', participant.identity);
    attachParticipant(participant);
}

function onParticipantDisconnected(participant) {
    console.log('Participant left:', participant.identity);
    detachParticipant(participant.identity);
}

function onTrackSubscribed(track, publication, participant) {
    console.log('Track subscribed:', participant.identity, track.kind, publication.source);
    attachParticipant(participant);
}

function onTrackUnsubscribed(track, publication, participant) {
    console.log('Track unsubscribed:', participant.identity, track.kind);
    // If video track removed, panel may be empty. Keep it, update if needed.
    const panel = remotePanels.get(participant.identity);
    if (panel && track.kind === 'video' && publication.source === Track.Source.Camera) {
        if (panel.videoEl) panel.videoEl.srcObject = null;
    }
}

function onLocalTrackPublished(publication) {
    if (publication.source === Track.Source.Camera && publication.videoTrack) {
        publication.videoTrack.attach(document.getElementById('local-video'));
    }
}

function onDataReceived(payload, participant, kind, topic) {
    console.log('[chat] DataReceived:', {
        payloadSize: payload ? payload.byteLength : 0,
        from: participant ? participant.identity : '(self)',
        kind, topic
    });
    try {
        const text = new TextDecoder().decode(payload);
        console.log('[chat] decoded:', text);
        const msg = JSON.parse(text);
        if (msg.type === 'chat') {
            appendChatMessage(participant ? participant.identity : 'unknown', msg.text);
        } else {
            console.warn('[chat] not a chat message:', msg);
        }
    } catch (e) { console.warn('Bad datachannel payload:', e); }
}

// ---------------------------------------------------------------------
// video panel management
// ---------------------------------------------------------------------
// =====================================================================
// Universal fullscreen (iOS Safari + Android + desktop)
// =====================================================================
function isFullscreenActive() {
    return !!(document.fullscreenElement || document.webkitFullscreenElement);
}

function toggleFullscreen(wrapperOrVideo) {
    if (!wrapperOrVideo) return;
    if (isFullscreenActive()) { exitFullscreen(); return; }

    let video = wrapperOrVideo.tagName === 'VIDEO'
        ? wrapperOrVideo
        : wrapperOrVideo.querySelector('video');

    if (wrapperOrVideo.requestFullscreen) {
        wrapperOrVideo.requestFullscreen().catch(err => {
            console.warn('requestFullscreen failed, trying webkit', err);
            tryWebkitFullscreen(video, wrapperOrVideo);
        });
        return;
    }
    if (wrapperOrVideo.webkitRequestFullscreen) {
        wrapperOrVideo.webkitRequestFullscreen();
        return;
    }
    tryWebkitFullscreen(video, wrapperOrVideo);
}

function tryWebkitFullscreen(video, wrapper) {
    if (video && video.webkitEnterFullscreen) {
        try { video.webkitEnterFullscreen(); return; }
        catch (e) { console.warn('webkitEnterFullscreen failed', e); }
    }
    if (wrapper && wrapper.webkitRequestFullscreen) {
        wrapper.webkitRequestFullscreen();
    }
}

function exitFullscreen() {
    if (document.exitFullscreen)               document.exitFullscreen().catch(() => {});
    else if (document.webkitExitFullscreen)    document.webkitExitFullscreen();
    else if (document.webkitCancelFullScreen)  document.webkitCancelFullScreen();
}
function closeFullscreen() { exitFullscreen(); }

function attachDoubleTapFullscreen(el) {
    let lastTap = 0;
    el.addEventListener('touchend', (e) => {
        const now = Date.now();
        if (now - lastTap < 300) {
            e.preventDefault();
            toggleFullscreen(el);
        }
        lastTap = now;
    }, { passive: false });
}

function attachParticipant(participant) {
    const id = participant.identity;
    const label = participant.name || id.slice(0, 6);

    let panel = remotePanels.get(id);
    if (!panel) {
        const wrapper = document.createElement('div');
        wrapper.id = 'remote-' + id;
        wrapper.className = 'remote-video-wrapper';

        const video = document.createElement('video');
        video.autoplay = true;
        video.playsInline = true;

        const lbl = document.createElement('div');
        lbl.className = 'video-label';
        lbl.textContent = label;

        // Кнопка fullscreen в углу
        const fsBtn = document.createElement('button');
        fsBtn.className = 'fullscreen-btn';
        fsBtn.title = 'Полный экран';
        fsBtn.innerHTML = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"/></svg>';
        fsBtn.onclick = (e) => { e.stopPropagation(); toggleFullscreen(wrapper); };

        wrapper.appendChild(video);
        wrapper.appendChild(lbl);
        wrapper.appendChild(fsBtn);
        attachDoubleTapFullscreen(wrapper);
        document.getElementById('remote-videos-grid').appendChild(wrapper);

        panel = { wrapperEl: wrapper, videoEl: video, labelEl: lbl, stream: new MediaStream() };
        remotePanels.set(id, panel);
    }

    // Attach all currently subscribed tracks.
    // Screen share has higher priority than camera: if present, replace main video.
    let hasScreenShare = false;
    participant.trackPublications.forEach(pub => {
        if (!pub.isSubscribed || !pub.track) return;
        if (pub.kind === 'audio') {
            pub.track.attach(panel.videoEl);
            return;
        }
        if (pub.kind === 'video' && pub.source === Track.Source.ScreenShare) {
            hasScreenShare = true;
            pub.track.attach(panel.videoEl);
            panel.labelEl.textContent = (participant.name || id.slice(0,6)) + ' (экран)';
            panel.wrapperEl.classList.add('showing-screen');
        }
    });
    // Camera — only if no screen share active
    if (!hasScreenShare) {
        participant.trackPublications.forEach(pub => {
            if (!pub.isSubscribed || !pub.track) return;
            if (pub.kind === 'video' && pub.source === Track.Source.Camera) {
                pub.track.attach(panel.videoEl);
                panel.labelEl.textContent = participant.name || id.slice(0,6);
                panel.wrapperEl.classList.remove('showing-screen');
            }
        });
    }
}

function detachParticipant(identity) {
    const panel = remotePanels.get(identity);
    if (!panel) return;
    try {
        panel.videoEl.srcObject = null;
        panel.wrapperEl.remove();
    } catch (e) {}
    remotePanels.delete(identity);
}

// ---------------------------------------------------------------------
// controls
// ---------------------------------------------------------------------
async function toggleMic() {
    if (!room) return;
    const wasEnabled = room.localParticipant.isMicrophoneEnabled;
    try {
        if (wasEnabled) {
            const pub = room.localParticipant.getTrackPublication(Track.Source.Microphone);
            if (pub && pub.track) {
                try { await room.localParticipant.unpublishTrack(pub.track, true); } catch (e) {}
                try { pub.track.stop(); } catch (e) {}
            }
        } else {
            await room.localParticipant.setMicrophoneEnabled(true);
        }
        const micOn = document.getElementById('mic-icon-on');
        const micOff = document.getElementById('mic-icon-off');
        if (micOn && micOff) {
            micOn.style.display = wasEnabled ? 'none' : '';
            micOff.style.display = wasEnabled ? '' : 'none';
        }
    } catch (e) { console.warn('toggleMic failed', e); }
}

async function toggleCam() {
    if (!room) return;
    const wasEnabled = room.localParticipant.isCameraEnabled;
    const btn = document.getElementById('toggle-cam');
    if (btn) btn.disabled = true;
    try {
        if (wasEnabled) {
            // Правильный путь: unpublish + LocalTrack.stop()
            // LocalTrack.stop() останавливает физический MediaStreamTrack
            // И корректно чистит состояние SDK → LED гаснет
            const pub = room.localParticipant.getTrackPublication(Track.Source.Camera);
            if (pub && pub.track) {
                try { await room.localParticipant.unpublishTrack(pub.track, true); } catch (e) {}
                try { pub.track.stop(); } catch (e) {}
            }
            const lv = document.getElementById('local-video');
            if (lv) lv.srcObject = null;
        } else {
            // setCameraEnabled(true) захватывает СВЕЖИЙ трек
            await room.localParticipant.setCameraEnabled(true);
            await new Promise(r => setTimeout(r, 250));
            const pub = room.localParticipant.getTrackPublication(Track.Source.Camera);
            const lv = document.getElementById('local-video');
            if (pub && pub.videoTrack && lv) {
                pub.videoTrack.attach(lv);
            }
        }
        const camOn = document.getElementById('cam-icon-on');
        const camOff = document.getElementById('cam-icon-off');
        if (camOn && camOff) {
            camOn.style.display = wasEnabled ? 'none' : '';
            camOff.style.display = wasEnabled ? '' : 'none';
        }
    } catch (e) {
        console.warn('toggleCam failed', e);
    } finally {
        if (btn) btn.disabled = false;
    }
}

async function toggleScreenShare() {
    if (!room) return;
    const btn = document.getElementById('toggle-screen');
    const currently = room.localParticipant.isScreenShareEnabled;
    try {
        await room.localParticipant.setScreenShareEnabled(!currently, {
            videoEncoding: {
                maxBitrate: 4_000_000,
                maxFramerate: 30
            },
            simulcast: true,
            degradationPreference: 'maintain-resolution'
        });
        if (btn) btn.classList.toggle('active', !currently);
    } catch (e) {
        console.warn('Screen share failed:', e);
        alert('Не удалось начать трансляцию экрана: ' + e.message);
    }
}

function leaveCall() {
    if (room) {
        try { room.disconnect(); } catch (e) {}
        room = null;
    }
    leaveCallUI();
    showRatingModal();
}

function leaveCallUI() {
    // stop local preview
    const localVideo = document.getElementById('local-video');
    if (localVideo) localVideo.srcObject = null;

    // remove all remote panels
    remotePanels.forEach(p => { try { p.wrapperEl.remove(); } catch (e) {} });
    remotePanels.clear();

    setSecurityBar(false);
    document.getElementById('call-screen').style.display = 'none';
    document.getElementById('main-screen').style.display = 'block';
}


// =====================================================================
// Sprint 3 — Chat via LiveKit DataChannel (E2EE, no server storage)
// =====================================================================
const CHAT_TOPIC = 'vidma-chat';
let chatOpen = false;
let chatUnread = 0;
const chatHistory = new Map(); // roomId -> [{sender, text, ts, mine}]

function chatStorageKey(roomId) { return 'vidma-chat-' + roomId; }

function loadChatHistory(roomId) {
    if (!roomId) return [];
    if (chatHistory.has(roomId)) return chatHistory.get(roomId);
    try {
        const raw = localStorage.getItem(chatStorageKey(roomId));
        const arr = raw ? JSON.parse(raw) : [];
        chatHistory.set(roomId, arr);
        return arr;
    } catch (e) {
        chatHistory.set(roomId, []);
        return [];
    }
}

function saveChatHistory(roomId, msgs) {
    if (!roomId) return;
    chatHistory.set(roomId, msgs);
    try { localStorage.setItem(chatStorageKey(roomId), JSON.stringify(msgs)); }
    catch (e) { console.warn('chat save failed', e); }
}

function formatChatTime(ts) {
    const d = new Date(ts || Date.now());
    const hh = String(d.getHours()).padStart(2, '0');
    const mm = String(d.getMinutes()).padStart(2, '0');
    return hh + ':' + mm;
}

function renderChatMessage(msg) {
    const box = document.getElementById('chat-messages');
    if (!box) return;
    const empty = document.getElementById('chat-empty');
    if (empty) empty.remove();

    const el = document.createElement('div');
    el.className = 'chat-msg ' + (msg.system ? 'system' : (msg.mine ? 'mine' : 'theirs'));
    if (!msg.system) {
        const a = document.createElement('span');
        a.className = 'chat-author';
        a.textContent = msg.mine ? 'Вы' : (msg.sender || 'Участник');
        el.appendChild(a);
    }
    const textNode = document.createTextNode(msg.text);
    el.appendChild(textNode);
    if (!msg.system) {
        const t = document.createElement('span');
        t.className = 'chat-time';
        t.textContent = formatChatTime(msg.ts);
        el.appendChild(t);
    }
    box.appendChild(el);
    box.scrollTop = box.scrollHeight;
}

function renderChatHistory(roomId) {
    const box = document.getElementById('chat-messages');
    if (!box) return;
    box.innerHTML = '';
    const msgs = loadChatHistory(roomId);
    if (msgs.length === 0) {
        const e = document.createElement('div');
        e.id = 'chat-empty';
        e.textContent = 'История чата видна только вам и хранится в этом браузере.';
        box.appendChild(e);
        return;
    }
    msgs.forEach(renderChatMessage);
}

function appendChatMessage(from, text) {
    // from === currentSessionId → mine; else theirs
    const isMine = (from === currentSessionId);
    const msg = {
        sender: isMine ? null : (room?.remoteParticipants?.get?.(from)?.name || from),
        text: String(text).slice(0, 500),
        ts: Date.now(),
        mine: isMine
    };
    const arr = loadChatHistory(currentRoomId);
    arr.push(msg);
    if (arr.length > 500) arr.splice(0, arr.length - 500);
    saveChatHistory(currentRoomId, arr);

    renderChatMessage(msg);

    if (!chatOpen && !isMine) {
        chatUnread++;
        updateChatBadge();
        playChatPing();
        showToast('Новое сообщение в чате');
    }
}

let __chatAudioCtx = null;
function playChatPing() {
    try {
        if (!__chatAudioCtx) {
            __chatAudioCtx = new (window.AudioContext || window.webkitAudioContext)();
        }
        const ctx = __chatAudioCtx;
        if (ctx.state === 'suspended') ctx.resume();
        const t0 = ctx.currentTime;
        // Мягкий "блип" из двух коротких тонов
        const osc = ctx.createOscillator();
        const gain = ctx.createGain();
        osc.type = 'sine';
        osc.frequency.setValueAtTime(880, t0);
        osc.frequency.setValueAtTime(1175, t0 + 0.08);
        gain.gain.setValueAtTime(0.0001, t0);
        gain.gain.exponentialRampToValueAtTime(0.15, t0 + 0.015);
        gain.gain.exponentialRampToValueAtTime(0.0001, t0 + 0.22);
        osc.connect(gain).connect(ctx.destination);
        osc.start(t0);
        osc.stop(t0 + 0.25);
    } catch (e) { /* тихо игнорируем */ }
}

function updateChatBadge() {
    const badge = document.getElementById('chat-badge');
    const btn = document.getElementById('toggle-chat');
    if (!badge || !btn) return;
    if (chatUnread > 0) {
        badge.textContent = chatUnread > 99 ? '99+' : String(chatUnread);
        btn.classList.add('has-unread');
    } else {
        badge.textContent = '0';
        btn.classList.remove('has-unread');
    }
}

function toggleChatPanel() {
    chatOpen = !chatOpen;
    const panel = document.getElementById('chat-panel');
    if (panel) panel.classList.toggle('open', chatOpen);
    if (chatOpen) {
        chatUnread = 0;
        updateChatBadge();
        renderChatHistory(currentRoomId);
        setTimeout(() => document.getElementById('chat-input')?.focus(), 50);
    }
}

function handleChatSubmit(ev) {
    ev.preventDefault();
    const input = document.getElementById('chat-input');
    if (!input) return;
    const text = input.value.trim();
    if (!text) return;
    sendChatMessage(text).then(() => {
        input.value = '';
    }).catch(e => {
        console.warn('send failed', e);
        showToast('Не удалось отправить сообщение');
    });
}

async function sendChatMessage(text) {
    if (!room || !text) { console.warn('[chat] sendChatMessage: no room or text'); return; }
    if (!room.localParticipant || !room.localParticipant.publishData) {
        console.warn('[chat] publishData not available'); return;
    }
    const payload = new TextEncoder().encode(JSON.stringify({
        type: 'chat', text: String(text).slice(0, 500)
    }));
    console.log('[chat] publishData: size=', payload.byteLength, 'topic=', CHAT_TOPIC);
    try {
        await room.localParticipant.publishData(payload, {
            reliable: true,
            topic: CHAT_TOPIC
        });
        console.log('[chat] publishData: OK');
    } catch (e) {
        console.error('[chat] publishData FAILED:', e);
        showToast('Не удалось отправить');
        throw e;
    }
    appendChatMessage(currentSessionId, text);
}

function showRatingModal() {
    const modal = document.getElementById('rating-modal');
    if (!modal) return;
    modal.classList.add('active');
    const stars = document.querySelectorAll('#stars span');
    stars.forEach(star => {
        star.onclick = () => {
            selectedRating = parseInt(star.dataset.value, 10);
            stars.forEach(s => s.classList.remove('active'));
            for (let i = 0; i < selectedRating; i++) stars[i].classList.add('active');
        };
    });
}

function closeRating() {
    const modal = document.getElementById('rating-modal');
    if (modal) modal.classList.remove('active');
    selectedRating = 0;
    const stars = document.querySelectorAll('#stars span');
    stars.forEach(s => s.classList.remove('active'));
}

function submitRating() {
    const commentEl = document.getElementById('rating-comment');
    const comment = commentEl ? commentEl.value.trim().slice(0, 500) : '';
    const rating = selectedRating;

    // Отправляем если есть хоть что-то (оценка или комментарий)
    if (rating > 0 || comment.length > 0) {
        fetch('/api/feedback', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                roomId: currentRoomId || 'unknown',
                rating: rating,
                comment: comment,
                userAgent: (navigator.userAgent || '').slice(0, 200)
            })
        }).then(r => r.json())
          .then(d => console.log('[feedback] sent:', d))
          .catch(e => console.warn('[feedback] failed:', e));
    }

    if (commentEl) commentEl.value = '';
    closeRating();
}

// ---------------------------------------------------------------------
// camera-permission retry from modal
// ---------------------------------------------------------------------
async function retryCamera() {
    const modal = document.getElementById('camera-choice-modal');
    if (modal) modal.classList.remove('active');
    if (!room) return;
    try {
        await room.localParticipant.enableCameraAndMicrophone();
    } catch (e) {
        if (modal) modal.classList.add('active');
    }
}

async function joinWithoutCamera() {
    const modal = document.getElementById('camera-choice-modal');
    if (modal) modal.classList.remove('active');
    if (!room) return;
    try {
        await room.localParticipant.setMicrophoneEnabled(true);
        await room.localParticipant.setCameraEnabled(false);
    } catch (e) { console.warn(e); }
}

// ---------------------------------------------------------------------
// URL ?room= auto-fill
// ---------------------------------------------------------------------
document.addEventListener('DOMContentLoaded', () => {
    // Разбудить AudioContext при первом клике — политика браузера
    const resumeAudio = () => {
        try {
            if (!__chatAudioCtx) {
                __chatAudioCtx = new (window.AudioContext || window.webkitAudioContext)();
            }
            if (__chatAudioCtx.state === 'suspended') __chatAudioCtx.resume();
        } catch (e) {}
        document.removeEventListener('click', resumeAudio);
        document.removeEventListener('touchstart', resumeAudio);
    };
    document.addEventListener('click', resumeAudio);
    document.addEventListener('touchstart', resumeAudio);

    const inp = document.getElementById('room-id');
    if (!inp) return;

    inp.addEventListener('input', (e) => {
        const itype = e.inputType || '';
        if (itype.startsWith('delete')) return;
        const digits = e.target.value.replace(/\D/g, '').slice(0, 9);
        let fmt = digits;
        if (digits.length >= 7)      fmt = digits.slice(0,3)+'-'+digits.slice(3,6)+'-'+digits.slice(6);
        else if (digits.length === 6) fmt = digits.slice(0,3)+'-'+digits.slice(3,6)+'-';
        else if (digits.length >= 4) fmt = digits.slice(0,3)+'-'+digits.slice(3);
        else if (digits.length === 3) fmt = digits+'-';
        e.target.value = fmt;
        e.target.setSelectionRange(fmt.length, fmt.length);
    });

    const urlRoom = new URLSearchParams(location.search).get('room');
    if (urlRoom) {
        const digits = urlRoom.replace(/\D/g, '').slice(0, 9);
        let fmt = digits;
        if (digits.length >= 7)      fmt = digits.slice(0,3)+'-'+digits.slice(3,6)+'-'+digits.slice(6);
        else if (digits.length === 6) fmt = digits.slice(0,3)+'-'+digits.slice(3,6)+'-';
        else if (digits.length >= 4) fmt = digits.slice(0,3)+'-'+digits.slice(3);
        else if (digits.length === 3) fmt = digits+'-';
        inp.value = fmt;
    }
});

// expose to inline onclick handlers in HTML
window.createRoom = createRoom;
window.copyRoomLink = copyRoomLink;
window.joinCreatedRoom = joinCreatedRoom;
window.joinRoom = joinRoom;
window.showLobby = showLobby;
window.lobbyToggleMic = lobbyToggleMic;
window.lobbyToggleCam = lobbyToggleCam;
window.cancelLobby = cancelLobby;
window.confirmLobbyEntry = confirmLobbyEntry;
window.toggleMic = toggleMic;
window.toggleCam = toggleCam;
window.toggleScreenShare = toggleScreenShare;
window.leaveCall = leaveCall;
window.submitRating = submitRating;
window.closeRating = closeRating;
window.retryCamera = retryCamera;
window.joinWithoutCamera = joinWithoutCamera;
window.shareRoomFromCall = copyRoomLink;
window.toggleChatPanel = toggleChatPanel;
window.handleChatSubmit = handleChatSubmit;
)js";

#endif // VIDMA_JS_H
