// Auto-generated by patch_client_livekit.py — LiveKit SDK edition
#ifndef VIDMA_JS_H
#define VIDMA_JS_H

constexpr const char* VIDMA_JS = R"js(
// =====================================================================
// Vidma client — LiveKit SDK edition (Sprint 2)
// =====================================================================
'use strict';

const { Room, RoomEvent, Track, ConnectionState, DisconnectReason } = LivekitClient;

let room = null;
let currentRoomId = null;
let currentName = null;
let currentSessionId = null;   // server-issued identity
let selectedRating = 0;

// map: participantIdentity -> { wrapperEl, videoEl, stream }
const remotePanels = new Map();
const remoteScreenPanels = new Map();  // отдельные панели для трансляции экрана

// ---------------------------------------------------------------------
// util
// ---------------------------------------------------------------------
function showToast(text) {
    const t = document.getElementById('toast');
    if (!t) return;
    t.textContent = text;
    t.classList.add('show');
    setTimeout(() => t.classList.remove('show'), 2000);
}

function setSecurityBar(visible) {
    const b = document.getElementById('security-bar');
    if (b) b.style.display = visible ? 'flex' : 'none';
}

function setLocalVideoLabel(txt) {
    const el = document.getElementById('local-video-label');
    if (el) el.textContent = txt;
}

// ---------------------------------------------------------------------
// room creation / joining
// ---------------------------------------------------------------------
async function createRoom() {
    let name = (document.getElementById('create-name')?.value || '').trim() || i18nT('placeholder.guest');
    console.log('[createRoom] name =', name);
    try {
        const res = await fetch('/api/room/create', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ name })
        });
        const data = await res.json();
        if (!data.success) { showToast(i18nT('error.createRoom')); return; }
        currentRoomId = data.roomId;
        currentName = name;
        document.getElementById('created-room-id').textContent = data.roomId;
        document.getElementById('room-created').style.display = 'block';
    } catch (e) {
        showToast(i18nT('error.connection'));
        console.error(e);
    }
}

function copyRoomLink() {
    if (!currentRoomId) return;
    const link = location.origin + '/?room=' + currentRoomId;
    const text = i18nT('link.share') + '\n' + link;
    navigator.clipboard.writeText(text).then(() => showToast(i18nT('toast.linkCopied')));
}

function joinCreatedRoom() {
    const freshName = (document.getElementById('create-name')?.value || '').trim();
    if (freshName) currentName = freshName;
    console.log('[joinCreatedRoom]', { currentRoomId: currentRoomId, currentName: currentName });
    if (currentRoomId && currentName) joinRoomById(currentRoomId, currentName);
}

async function joinRoom() {
    let name = (document.getElementById('join-name')?.value || '').trim() || i18nT('placeholder.guest');
    console.log('[joinRoom] name =', name);
    let raw = (document.getElementById('room-id')?.value || '').trim();
    const digits = raw.replace(/\D/g, '');
    if (digits.length !== 9) { alert(i18nT('error.invalidCode')); return; }
    const roomId = digits.slice(0,3) + '-' + digits.slice(3,6) + '-' + digits.slice(6,9);
    try {
        const res = await fetch('/api/room/' + roomId + '/exists');
        const data = await res.json();
        if (!data.exists) { alert(i18nT('error.roomNotFound')); return; }
        joinRoomById(roomId, name);
    } catch (e) { alert(i18nT('error.connection')); }
}

async function joinRoomById(roomId, name) {
    currentRoomId = roomId;
    currentName = name;
    await showLobby(roomId, name);
}

// =====================================================================
// Lobby — preview, device picker, audio level, separate permissions
// =====================================================================
const lobbyState = {
    stream: null,
    audioCtx: null,
    analyser: null,
    levelRaf: null,
    micEnabled: true,
    camEnabled: true,
};

function resolveName(preferredName) {
    if (preferredName && !isGuestName(preferredName)) return String(preferredName).trim();
    try {
        if (typeof currentName !== 'undefined' && currentName && !isGuestName(currentName)) {
            return String(currentName).trim();
        }
    } catch (e) {}
    const cv = (document.getElementById('create-name')?.value || '').trim();
    if (cv && !isGuestName(cv)) return cv;
    const jv = (document.getElementById('join-name')?.value || '').trim();
    if (jv && !isGuestName(jv)) return jv;
    return 'Гость';
}


// =====================================================================
// i18n — internationalization engine
// =====================================================================
const I18N_SUPPORTED = ['en', 'ru', 'es', 'de', 'fr', 'zh', 'ja', 'pt'];
const I18N_DEFAULT = 'en';
let i18nTranslations = {};
let i18nCurrent = I18N_DEFAULT;

function i18nDetect() {
    // 1. localStorage
    try {
        const saved = localStorage.getItem('vidma-lang');
        if (saved && I18N_SUPPORTED.includes(saved)) return saved;
    } catch (e) {}
    // 2. navigator.language(s)
    const navs = navigator.languages || [navigator.language || navigator.userLanguage || ''];
    for (const l of navs) {
        const short = String(l).toLowerCase().split('-')[0];
        if (I18N_SUPPORTED.includes(short)) return short;
    }
    return I18N_DEFAULT;
}

function i18nT(key, fallback) {
    const dict = i18nTranslations[i18nCurrent] || {};
    if (dict[key] !== undefined) return dict[key];
    const def = i18nTranslations[I18N_DEFAULT] || {};
    if (def[key] !== undefined) return def[key];
    return fallback !== undefined ? fallback : key;
}

function i18nApplyAll() {
    // Text nodes
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const val = i18nT(key);
        if (val !== undefined && val !== null) el.textContent = val;
    });
    // Placeholders
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        el.placeholder = i18nT(key);
    });
    // Titles
    document.querySelectorAll('[data-i18n-title]').forEach(el => {
        const key = el.getAttribute('data-i18n-title');
        el.title = i18nT(key);
    });
    // html lang attr
    document.documentElement.setAttribute('lang', i18nCurrent);
}

async function i18nLoad() {
    try {
        const res = await fetch('/translations.json', { cache: 'no-store' });
        i18nTranslations = await res.json();
    } catch (e) {
        console.warn('[i18n] failed to load translations', e);
        i18nTranslations = {};
    }
    i18nCurrent = i18nDetect();
    i18nApplyAll();
    vidmaUpdateLangUI();
}

function i18nSetLang(lang) {
    if (!I18N_SUPPORTED.includes(lang)) return;
    i18nCurrent = lang;
    try { localStorage.setItem('vidma-lang', lang); } catch (e) {}
    i18nApplyAll();
    vidmaUpdateLangUI();
    // Re-render dynamic parts that were created in JS with hardcoded text
    if (typeof renderChatHistory === 'function' && currentRoomId) {
        try { renderChatHistory(currentRoomId); } catch (e) {}
    }
}



// =====================================================================
// Custom language dropdown
// =====================================================================
const LANG_META = {
    en: { name: 'English',  flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="24" height="16" fill="#012169"/><path d="M0,0 L24,16 M24,0 L0,16" stroke="#fff" stroke-width="3.2"/><path d="M0,0 L24,16 M24,0 L0,16" stroke="#C8102E" stroke-width="1.6"/><path d="M12,0 L12,16 M0,8 L24,8" stroke="#fff" stroke-width="5.3"/><path d="M12,0 L12,16 M0,8 L24,8" stroke="#C8102E" stroke-width="3.2"/></svg>' },
    ru: { name: 'Русский', flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="24" height="5.33" fill="#fff"/><rect y="5.33" width="24" height="5.33" fill="#0039A6"/><rect y="10.66" width="24" height="5.34" fill="#D52B1E"/></svg>' },
    es: { name: 'Español', flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="24" height="16" fill="#AA151B"/><rect y="4" width="24" height="8" fill="#F1BF00"/></svg>' },
    de: { name: 'Deutsch', flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="24" height="5.33" fill="#000"/><rect y="5.33" width="24" height="5.33" fill="#DD0000"/><rect y="10.66" width="24" height="5.34" fill="#FFCE00"/></svg>' },
    fr: { name: 'Français', flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="8" height="16" fill="#002395"/><rect x="8" width="8" height="16" fill="#fff"/><rect x="16" width="8" height="16" fill="#ED2939"/></svg>' },
    zh: { name: '中文', flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="24" height="16" fill="#DE2910"/><polygon points="4.5,2.5 5.6,5.6 2.6,3.4 6.4,3.4 3.4,5.6" fill="#FFDE00"/></svg>' },
    ja: { name: '日本語', flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="24" height="16" fill="#fff"/><circle cx="12" cy="8" r="4.4" fill="#BC002D"/></svg>' },
    pt: { name: 'Português', flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="9.6" height="16" fill="#006600"/><rect x="9.6" width="14.4" height="16" fill="#FF0000"/><circle cx="9.6" cy="8" r="3.3" fill="#FFCC00" stroke="#fff" stroke-width="0.4"/></svg>' }
};





// Close menu on outside click / Esc
document.addEventListener('click', (e) => {
    const sw = document.getElementById('lang-switcher');
    if (sw && !sw.contains(e.target)) closeLangMenu();
});
document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') closeLangMenu();
});


// =====================================================================
// Custom language dropdown (fixed top-right)
// =====================================================================
const VIDMA_LANG_META = {
    en: { name: 'English',  flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="24" height="16" fill="#012169"/><path d="M0,0 L24,16 M24,0 L0,16" stroke="#fff" stroke-width="3.2"/><path d="M0,0 L24,16 M24,0 L0,16" stroke="#C8102E" stroke-width="1.6"/><path d="M12,0 L12,16 M0,8 L24,8" stroke="#fff" stroke-width="5.3"/><path d="M12,0 L12,16 M0,8 L24,8" stroke="#C8102E" stroke-width="3.2"/></svg>' },
    ru: { name: 'Русский', flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="24" height="5.33" fill="#fff"/><rect y="5.33" width="24" height="5.33" fill="#0039A6"/><rect y="10.66" width="24" height="5.34" fill="#D52B1E"/></svg>' },
    es: { name: 'Español', flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="24" height="16" fill="#AA151B"/><rect y="4" width="24" height="8" fill="#F1BF00"/></svg>' },
    de: { name: 'Deutsch', flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="24" height="5.33" fill="#000"/><rect y="5.33" width="24" height="5.33" fill="#DD0000"/><rect y="10.66" width="24" height="5.34" fill="#FFCE00"/></svg>' },
    fr: { name: 'Français', flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="8" height="16" fill="#002395"/><rect x="8" width="8" height="16" fill="#fff"/><rect x="16" width="8" height="16" fill="#ED2939"/></svg>' },
    zh: { name: '中文', flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="24" height="16" fill="#DE2910"/><polygon points="4.5,2.5 5.6,5.6 2.6,3.4 6.4,3.4 3.4,5.6" fill="#FFDE00"/></svg>' },
    ja: { name: '日本語', flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="24" height="16" fill="#fff"/><circle cx="12" cy="8" r="4.4" fill="#BC002D"/></svg>' },
    pt: { name: 'Português', flag: '<svg viewBox="0 0 24 16" preserveAspectRatio="none"><rect width="9.6" height="16" fill="#006600"/><rect x="9.6" width="14.4" height="16" fill="#FF0000"/><circle cx="9.6" cy="8" r="3.3" fill="#FFCC00" stroke="#fff" stroke-width="0.4"/></svg>' }
};

function vidmaToggleLang(e) {
    if (e) { e.stopPropagation(); e.preventDefault(); }
    const root = document.getElementById('vidma-lang-root');
    if (!root) return;
    const open = root.classList.toggle('open');
    const btn = document.getElementById('vidma-lang-btn');
    if (btn) btn.setAttribute('aria-expanded', open ? 'true' : 'false');
}

function vidmaCloseLang() {
    const root = document.getElementById('vidma-lang-root');
    if (root) root.classList.remove('open');
    const btn = document.getElementById('vidma-lang-btn');
    if (btn) btn.setAttribute('aria-expanded', 'false');
}

function vidmaPickLang(lang, e) {
    if (e) { e.stopPropagation(); e.preventDefault(); }
    i18nSetLang(lang);
    vidmaCloseLang();
}

function vidmaUpdateLangUI() {
    const meta = VIDMA_LANG_META[i18nCurrent] || VIDMA_LANG_META.en;
    const nameEl = document.getElementById('vidma-current-name');
    const flagEl = document.getElementById('vidma-current-flag');
    if (nameEl) nameEl.textContent = meta.name;
    if (flagEl) flagEl.innerHTML = meta.flag;
    document.querySelectorAll('.vlang-item').forEach(item => {
        item.classList.toggle('active', item.dataset.lang === i18nCurrent);
    });
}

// Close on outside click / Esc
document.addEventListener('click', (e) => {
    const root = document.getElementById('vidma-lang-root');
    if (root && !root.contains(e.target)) vidmaCloseLang();
});
document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') vidmaCloseLang();
});

// Export to window
window.vidmaToggleLang = vidmaToggleLang;
window.vidmaCloseLang = vidmaCloseLang;
window.vidmaPickLang = vidmaPickLang;
window.vidmaUpdateLangUI = vidmaUpdateLangUI;


// =====================================================================
// Cookie consent
// =====================================================================
function acceptCookies() {
    try { localStorage.setItem('vidma-cookie-consent', '1'); } catch (e) {}
    const b = document.getElementById('cookie-banner');
    if (b) b.classList.remove('show');
}
function maybeShowCookieBanner() {
    let consent = null;
    try { consent = localStorage.getItem('vidma-cookie-consent'); } catch (e) {}
    if (!consent) {
        const b = document.getElementById('cookie-banner');
        if (b) setTimeout(() => b.classList.add('show'), 800);
    }
}
window.acceptCookies = acceptCookies;


// =====================================================================
// Invite modal
// =====================================================================
function openInviteModal() {
    const roomId = currentRoomId || '';
    const link = roomId
        ? 'https://vidma.online/?room=' + roomId
        : 'https://vidma.online/';
    const linkEl = document.getElementById('invite-link');
    if (linkEl) linkEl.textContent = link;
    const modal = document.getElementById('invite-modal');
    if (modal) modal.classList.add('active');
}

function closeInviteModal() {
    const modal = document.getElementById('invite-modal');
    if (modal) modal.classList.remove('active');
}

function getInviteLink() {
    if (currentRoomId) return 'https://vidma.online/?room=' + currentRoomId;
    return 'https://vidma.online/';
}

function getInviteText() {
    const t = (typeof i18nT === 'function') ? i18nT('invite.message') : 'Join my Vidma call:';
    return t + '\n' + getInviteLink();
}

function inviteCopy() {
    navigator.clipboard.writeText(getInviteText()).then(() => {
        showToast((typeof i18nT === 'function') ? i18nT('toast.linkCopied') : 'Link copied!');
    });
}

function inviteTelegram() {
    const url = 'https://t.me/share/url?url=' + encodeURIComponent(getInviteLink()) +
                '&text=' + encodeURIComponent((typeof i18nT === 'function') ? i18nT('invite.message') : 'Join my Vidma call');
    window.open(url, '_blank');
}

function inviteWhatsApp() {
    const url = 'https://wa.me/?text=' + encodeURIComponent(getInviteText());
    window.open(url, '_blank');
}

function inviteEmail() {
    const subject = (typeof i18nT === 'function') ? i18nT('invite.emailSubject') : 'Join my Vidma call';
    const body = getInviteText();
    window.location.href = 'mailto:?subject=' + encodeURIComponent(subject) + '&body=' + encodeURIComponent(body);
}

// Close on backdrop click
document.addEventListener('click', (e) => {
    const modal = document.getElementById('invite-modal');
    if (modal && e.target === modal) closeInviteModal();
});
document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') closeInviteModal();
});

window.openInviteModal = openInviteModal;
window.closeInviteModal = closeInviteModal;
window.inviteCopy = inviteCopy;
window.inviteTelegram = inviteTelegram;
window.inviteWhatsApp = inviteWhatsApp;
window.inviteEmail = inviteEmail;


// =====================================================================
// Top bars collapse (mobile-friendly)
// =====================================================================
function toggleTopBars() {
    const topBar = document.querySelector('#call-screen .top-bar');
    const btn = document.getElementById('toggle-bars-btn');
    if (!topBar || !btn) return;
    const isCollapsed = topBar.classList.toggle('collapsed');
    btn.classList.toggle('collapsed', isCollapsed);
    try { localStorage.setItem('vidma-topbars-collapsed', isCollapsed ? '1' : '0'); } catch (e) {}
    console.log('[topbar] collapsed =', isCollapsed);
}

function initTopBarsState() {
    const topBar = document.querySelector('#call-screen .top-bar');
    const btn = document.getElementById('toggle-bars-btn');
    if (!topBar || !btn) return;
    let collapsed = false;
    try {
        const saved = localStorage.getItem('vidma-topbars-collapsed');
        if (saved === '1') collapsed = true;
        else if (saved === '0') collapsed = false;
        else collapsed = window.innerWidth < 600;
    } catch (e) {
        collapsed = window.innerWidth < 600;
    }
    topBar.classList.toggle('collapsed', collapsed);
    btn.classList.toggle('collapsed', collapsed);
    btn.classList.add('visible');
}

window.toggleTopBars = toggleTopBars;
window.initTopBarsState = initTopBarsState;


// =====================================================================
// RNNoise suppression (pure WebAudio, no LiveKit dependency)
// =====================================================================
const NR_SUPPORTED = (function() {
    const ua = navigator.userAgent;
    const isMobile = /iPhone|iPad|iPod|Android/i.test(ua);
    const isSafari = /Safari/.test(ua) && !/Chrome|Chromium/.test(ua);
    return !isMobile && !isSafari && 'AudioWorklet' in window && 'AudioContext' in window;
})();

const NR_CDN = '/rnnoise';
let __nrEnabled = false;
let __nrAudioCtx = null;
let __nrNode = null;
let __nrSource = null;
let __nrDest = null;
let __nrProcessedTrack = null;

function updateNoiseToggleUI() {
    const toggle = document.getElementById('noise-toggle');
    const hint = document.getElementById('nr-hint');
    if (!toggle) return;
    if (!NR_SUPPORTED) {
        toggle.classList.add('disabled');
        toggle.classList.remove('on');
        if (hint) hint.textContent = '(' + i18nT('noise.unsupported') + ')';
        return;
    }
    toggle.classList.toggle('on', __nrEnabled);
    if (hint) hint.textContent = '';
}

function toggleNoiseSuppression() {
    if (!NR_SUPPORTED) {
        showToast(i18nT('noise.unsupported'));
        return;
    }
    __nrEnabled = !__nrEnabled;
    try { localStorage.setItem('vidma-noise', __nrEnabled ? '1' : '0'); } catch (e) {}
    updateNoiseToggleUI();
    updateSensitivityVisibility();
    console.log('[noise] enabled =', __nrEnabled);
    showToast(__nrEnabled ? i18nT('noise.on') : i18nT('noise.off'));
}

function isNoiseEnabled() {
    if (!NR_SUPPORTED) return false;
    try {
        const saved = localStorage.getItem('vidma-noise');
        if (saved === '1') return true;
        if (saved === '0') return false;
    } catch (e) {}
    return false; // по умолчанию ВЫКЛЮЧЕНО, пользователь включает сам
}

async function initRNNoiseWorklet() {
    if (__nrNode) return __nrNode;
    if (!NR_SUPPORTED) throw new Error('not supported');

    const mod = await import(NR_CDN + '/index.js');
    const { loadRnnoise, RnnoiseWorkletNode } = mod;

    const wasmBinary = await loadRnnoise({
        url: NR_CDN + '/rnnoise.wasm',
        simdUrl: NR_CDN + '/rnnoise_simd.wasm'
    });

    __nrAudioCtx = new (window.AudioContext || window.webkitAudioContext)({ sampleRate: 48000 });
    if (__nrAudioCtx.state === 'suspended') await __nrAudioCtx.resume();

    await __nrAudioCtx.audioWorklet.addModule(NR_CDN + '/rnnoise-worklet.js');
    __nrNode = new RnnoiseWorkletNode(__nrAudioCtx, { wasmBinary, maxChannels: 1 });
    console.log('[noise] RNNoise worklet loaded');
    return __nrNode;
}

// Возвращает НОВЫЙ аудиотрек с шумоподавлением
async function applyNoiseSuppression(stream) {
    if (!stream || !__nrEnabled || !NR_SUPPORTED) return stream;
    const audioTrack = stream.getAudioTracks()[0];
    if (!audioTrack) return stream;

    try {
        const node = await initRNNoiseWorklet();

        __nrSource = __nrAudioCtx.createMediaStreamSource(new MediaStream([audioTrack]));
        // Mono — RNNoise работает только с 1 каналом
        try {
            __nrSource.channelCount = 1;
            __nrSource.channelCountMode = 'explicit';
            __nrSource.channelInterpretation = 'speakers';
        } catch (e) {}

        __nrDest = __nrAudioCtx.createMediaStreamDestination();

        // Пред-гейн на основе чувствительности
        // Нейтральный граф: RNNoise сам нормализует громкость
        __nrSource.connect(node);
        node.connect(__nrDest);
        console.log('[noise] neutral graph');
        node.connect(__nrDest);

        // КРИТИЧНО: silent keep-alive — заставляет Chrome обрабатывать граф
        const silentSink = __nrAudioCtx.createGain();
        silentSink.gain.value = 0;
        node.connect(silentSink);
        silentSink.connect(__nrAudioCtx.destination);

        __nrProcessedTrack = __nrDest.stream.getAudioTracks()[0];
        __nrProcessedTrack.enabled = audioTrack.enabled;

        // Подменяем аудиотрек в stream
        stream.removeTrack(audioTrack);
        stream.addTrack(__nrProcessedTrack);

        console.log('[noise] RNNoise applied, new track:', __nrProcessedTrack.label);
    } catch (e) {
        console.warn('[noise] failed to apply RNNoise:', e);
        showToast(i18nT('noise.failed'));
    }

    return stream;
}


// =====================================================================
// Noise sensitivity (1-10)
// =====================================================================
let __nrSensitivity = 5;
let __nrPreGain = null;

function getSensitivity() {
    try {
        const v = parseInt(localStorage.getItem('vidma-noise-sens') || '5', 10);
        if (v >= 1 && v <= 10) return v;
    } catch (e) {}
    return 5;
}

function setSensitivity(v) {
    v = Math.max(1, Math.min(10, parseInt(v, 10) || 5));
    __nrSensitivity = v;
    try { localStorage.setItem('vidma-noise-sens', String(v)); } catch (e) {}
    const el = document.getElementById('nr-sens-value');
    if (el) el.textContent = String(v);
    const slider = document.getElementById('nr-sens-slider');
    if (slider) {
        if (parseInt(slider.value, 10) !== v) slider.value = String(v);
        // Обновляем заливку
        const pct = ((v - 1) / 9) * 100;
        slider.style.setProperty('--fill', pct + '%');
    }
    // Гейн фиксирован — не обновляем
}

// sensitivity 1 (только громкий голос) -> 0.8
// sensitivity 5 (средне) -> 2.0
// sensitivity 10 (любой голос) -> 4.5
function sensitivityToGain(s) {
    return 0.8 + ((s - 1) / 9) * 3.7;
}

function onSensitivityChange(v) {
    setSensitivity(v);
}

function updateSensitivityVisibility() {
    const row = document.getElementById('nr-sens-row');
    if (!row) return;
    row.classList.toggle('visible', __nrEnabled && NR_SUPPORTED);
}

window.onSensitivityChange = onSensitivityChange;
window.getSensitivity = getSensitivity;

function initNoiseToggle() {
    __nrEnabled = isNoiseEnabled();
    __nrSensitivity = getSensitivity();
    const el = document.getElementById('nr-sens-value');
    if (el) el.textContent = String(__nrSensitivity);
    const slider = document.getElementById('nr-sens-slider');
    if (slider) slider.value = String(__nrSensitivity);
    updateNoiseToggleUI();
    updateSensitivityVisibility();
    console.log('[noise] init, enabled =', __nrEnabled, 'sens =', __nrSensitivity, 'supported =', NR_SUPPORTED);
}

window.toggleNoiseSuppression = toggleNoiseSuppression;
window.initNoiseToggle = initNoiseToggle;
window.applyNoiseSuppression = applyNoiseSuppression;

function showLobby(roomId, name) {
    currentRoomId = roomId;

    // Собираем имя из всех возможных источников
    let candidate = '';
    if (name && !isGuestName(name)) candidate = String(name).trim();
    if (!candidate && currentName && !isGuestName(currentName)) candidate = String(currentName).trim();
    if (!candidate) {
        const cv = (document.getElementById('create-name')?.value || '').trim();
        if (cv && !isGuestName(cv)) candidate = cv;
    }
    if (!candidate) {
        const jv = (document.getElementById('join-name')?.value || '').trim();
        if (jv && !isGuestName(jv)) candidate = jv;
    }
    if (!candidate) {
        try {
            const lv = (localStorage.getItem('vidma-name') || '').trim();
            if (lv && !isGuestName(lv)) candidate = lv;
        } catch (e) {}
    }

    currentName = candidate || 'Гость';
    console.log('[showLobby] passed=%s resolved=%s', name, currentName);

    document.getElementById('main-screen').style.display = 'none';
    document.getElementById('call-screen').style.display = 'none';
    { const __b = document.getElementById('toggle-bars-btn'); if (__b) { __b.classList.remove('visible'); __b.style.display = 'none'; } }
    document.getElementById('lobby-screen').classList.add('active');
    if (typeof initNoiseToggle === 'function') initNoiseToggle();

    // Заполняем поле имени в лобби
    const nameInput = document.getElementById('lobby-name-input');
    if (nameInput) {
        nameInput.value = candidate || '';
        console.log('[showLobby] filled input with:', candidate || '(empty)');
        if (!candidate) setTimeout(() => nameInput.focus(), 300);
    } else {
        console.warn('[showLobby] lobby-name-input NOT FOUND in DOM');
    }

    return startLobbyPreview();
}

async function startLobbyPreview() {
    try {
        const stream = await navigator.mediaDevices.getUserMedia({
            video: { width: { ideal: 1280 }, height: { ideal: 720 } },
            audio: { echoCancellation: true, noiseSuppression: true, autoGainControl: true }
        });
        lobbyState.stream = stream;
        lobbyState.micEnabled = true;
        lobbyState.camEnabled = true;

        const vid = document.getElementById('lobby-video');
        vid.srcObject = stream;
        document.getElementById('lobby-preview-box').classList.remove('no-video');
        const micOn = document.getElementById('lobby-mic-svg-on');
        const micOff = document.getElementById('lobby-mic-svg-off');
        const camOn = document.getElementById('lobby-cam-svg-on');
        const camOff = document.getElementById('lobby-cam-svg-off');
        if (micOn) micOn.style.display = '';
        if (micOff) micOff.style.display = 'none';
        if (camOn) camOn.style.display = '';
        if (camOff) camOff.style.display = 'none';
        document.getElementById('lobby-mic-toggle').classList.add('on');
        document.getElementById('lobby-mic-toggle').classList.remove('off');
        document.getElementById('lobby-cam-toggle').classList.add('on');
        document.getElementById('lobby-cam-toggle').classList.remove('off');

        await populateLobbyDevices();
        startAudioLevelMeter();
    } catch (err) {
        console.warn('Lobby: getUserMedia failed', err);
        // Если пользователь отказал — просто показываем модалку выбора
        const modal = document.getElementById('camera-choice-modal');
        if (modal) modal.classList.add('active');
    }
}

async function populateLobbyDevices() {
    try {
        const devices = await navigator.mediaDevices.enumerateDevices();
        const micSel = document.getElementById('lobby-mic-select');
        const camSel = document.getElementById('lobby-cam-select');
        const currentMic = lobbyState.stream ? (lobbyState.stream.getAudioTracks()[0]?.getSettings().deviceId) : null;
        const currentCam = lobbyState.stream ? (lobbyState.stream.getVideoTracks()[0]?.getSettings().deviceId) : null;

        micSel.innerHTML = '';
        camSel.innerHTML = '';

        let micCount = 0, camCount = 0;
        devices.forEach(d => {
            if (d.kind === 'audioinput') {
                micCount++;
                const opt = document.createElement('option');
                opt.value = d.deviceId;
                opt.textContent = d.label || (i18nT('lobby.mic') + ' ' + micCount);
                if (currentMic && d.deviceId === currentMic) opt.selected = true;
                micSel.appendChild(opt);
            } else if (d.kind === 'videoinput') {
                camCount++;
                const opt = document.createElement('option');
                opt.value = d.deviceId;
                opt.textContent = d.label || (i18nT('lobby.camera') + ' ' + camCount);
                if (currentCam && d.deviceId === currentCam) opt.selected = true;
                camSel.appendChild(opt);
            }
        });

        micSel.onchange = () => switchLobbyDevice('audio', micSel.value);
        camSel.onchange = () => switchLobbyDevice('video', camSel.value);
    } catch (e) {
        console.warn('enumerateDevices failed', e);
    }
}

async function switchLobbyDevice(kind, deviceId) {
    if (!lobbyState.stream || !deviceId) return;
    try {
        const newStream = await navigator.mediaDevices.getUserMedia({
            [kind]: { deviceId: { exact: deviceId } }
        });
        const newTrack = newStream.getTracks()[0];
        // Убираем старые треки того же типа
        lobbyState.stream.getTracks()
            .filter(t => t.kind === kind)
            .forEach(t => { lobbyState.stream.removeTrack(t); t.stop(); });
        lobbyState.stream.addTrack(newTrack);

        if (kind === 'video') {
            document.getElementById('lobby-video').srcObject = lobbyState.stream;
        } else {
            startAudioLevelMeter();
        }
    } catch (e) {
        console.warn('switchLobbyDevice failed', e);
    }
}

function startAudioLevelMeter() {
    if (!lobbyState.stream) return;
    stopAudioLevelMeter();
    const audioTracks = lobbyState.stream.getAudioTracks();
    if (audioTracks.length === 0) return;

    try {
        const ctx = new (window.AudioContext || window.webkitAudioContext)();
        lobbyState.audioCtx = ctx;
        const src = ctx.createMediaStreamSource(new MediaStream(audioTracks));
        const analyser = ctx.createAnalyser();
        analyser.fftSize = 512;
        src.connect(analyser);
        lobbyState.analyser = analyser;

        const data = new Uint8Array(analyser.frequencyBinCount);
        const bar = document.getElementById('lobby-level-bar');

        const tick = () => {
            if (!lobbyState.analyser) return;
            analyser.getByteFrequencyData(data);
            let sum = 0;
            for (let i = 0; i < data.length; i++) sum += data[i];
            const avg = sum / data.length;
            const pct = Math.min(100, (avg / 128) * 100 * 2.2);
            bar.style.width = pct + '%';
            lobbyState.levelRaf = requestAnimationFrame(tick);
        };
        tick();
    } catch (e) {
        console.warn('audio meter failed', e);
    }
}

function stopAudioLevelMeter() {
    if (lobbyState.levelRaf) {
        cancelAnimationFrame(lobbyState.levelRaf);
        lobbyState.levelRaf = null;
    }
    if (lobbyState.audioCtx) {
        try { lobbyState.audioCtx.close(); } catch (e) {}
        lobbyState.audioCtx = null;
    }
    lobbyState.analyser = null;
    const bar = document.getElementById('lobby-level-bar');
    if (bar) bar.style.width = '0%';
}

function lobbyToggleMic() {
    if (!lobbyState.stream) return;
    lobbyState.micEnabled = !lobbyState.micEnabled;
    lobbyState.stream.getAudioTracks().forEach(t => t.enabled = lobbyState.micEnabled);
    const btn = document.getElementById('lobby-mic-toggle');
    const on = document.getElementById('lobby-mic-svg-on');
    const off = document.getElementById('lobby-mic-svg-off');
    if (on) on.style.display = lobbyState.micEnabled ? '' : 'none';
    if (off) off.style.display = lobbyState.micEnabled ? 'none' : '';
    btn.classList.toggle('on', lobbyState.micEnabled);
    btn.classList.toggle('off', !lobbyState.micEnabled);
}

function lobbyToggleCam() {
    if (!lobbyState.stream) return;
    lobbyState.camEnabled = !lobbyState.camEnabled;
    lobbyState.stream.getVideoTracks().forEach(t => t.enabled = lobbyState.camEnabled);
    const btn = document.getElementById('lobby-cam-toggle');
    const on = document.getElementById('lobby-cam-svg-on');
    const off = document.getElementById('lobby-cam-svg-off');
    if (on) on.style.display = lobbyState.camEnabled ? '' : 'none';
    if (off) off.style.display = lobbyState.camEnabled ? 'none' : '';
    btn.classList.toggle('on', lobbyState.camEnabled);
    btn.classList.toggle('off', !lobbyState.camEnabled);
    document.getElementById('lobby-preview-box').classList.toggle('no-video', !lobbyState.camEnabled);
}

function cancelLobby() {
    stopAudioLevelMeter();
    if (lobbyState.stream) {
        lobbyState.stream.getTracks().forEach(t => t.stop());
        lobbyState.stream = null;
    }
    document.getElementById('lobby-screen').classList.remove('active');
    document.getElementById('main-screen').style.display = 'block';
    document.getElementById('lobby-video').srcObject = null;
}

async function confirmLobbyEntry() {
    // ВАЖНО: имя берём из поля лобби — финальный источник правды
    const nameInput = document.getElementById('lobby-name-input');
    let finalName = '';
    if (nameInput) {
        finalName = (nameInput.value || '').trim();
        console.log('[confirmLobbyEntry] input value:', finalName);
    } else {
        console.warn('[confirmLobbyEntry] lobby-name-input NOT FOUND');
    }

    if (!finalName || isGuestName(finalName)) {
        if (currentName && !isGuestName(currentName)) {
            finalName = String(currentName).trim();
        } else {
            finalName = 'Гость';
        }
    }

    currentName = finalName;
    try {
        if (!isGuestName(finalName)) localStorage.setItem('vidma-name', finalName);
    } catch (e) {}

    console.log('[confirmLobbyEntry] FINAL name =', currentName);

    stopAudioLevelMeter();
    const stream = lobbyState.stream;
    if (stream) {
        stream.getVideoTracks().forEach(t => t.enabled = lobbyState.camEnabled);
        stream.getAudioTracks().forEach(t => t.enabled = lobbyState.micEnabled);
    }
    document.getElementById('lobby-screen').classList.remove('active');
    document.getElementById('call-screen').style.display = 'block';
    if (typeof initTopBarsState === 'function') initTopBarsState();
    document.getElementById('current-room-code').textContent = currentRoomId;
    setLocalVideoLabel(currentName + ' (' + i18nT('call.you') + ')');
    await applyNoiseSuppression(stream);
    await connectToRoom(stream);
}

// =====================================================================
// Real connection (uses already-obtained stream from lobby)
// =====================================================================
async function connectToRoom(preStream) {
    // currentName уже установлен confirmLobbyEntry — НЕ перезаписываем!
    console.log('[connectToRoom] name =', currentName);

    // 1. Get token from server
    let data;
    try {
        const res = await fetch('/api/room/' + currentRoomId + '/token', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ name: currentName })
        });
        data = await res.json();
        if (!data.livekitUrl || !data.livekitToken) {
            throw new Error('Server did not return livekit config');
        }
        // Log JWT payload to verify name made it into the token
        try {
            const parts = data.livekitToken.split('.');
            const pad = '='.repeat((4 - parts[1].length % 4) % 4);
            const payload = JSON.parse(atob((parts[1] + pad).replace(/-/g, '+').replace(/_/g, '/')));
            console.log('[JWT payload]', payload);
        } catch (e) {}
    } catch (e) {
        alert(i18nT('error.token') + ' ' + e.message);
        leaveCall();
        return;
    }
    currentSessionId = data.identity;

    // 2. Create room
    room = new Room({
        adaptiveStream: true,
        dynacast: true,
        videoCaptureDefaults: {
            resolution: { width: 1280, height: 720, frameRate: 30 }
        },
        audioCaptureDefaults: {
            echoCancellation: true,
            noiseSuppression: true,
            autoGainControl: true,
            sampleRate: 48000,
            channelCount: 1
        },
        publishDefaults: {
            simulcast: true,
            videoSimulcastLayers: undefined,
            videoCodec: 'vp8',
            dtx: true,
            red: true
        }
    });

    // 3. Event handlers
    room
        .on(RoomEvent.Connected, onConnected)
        .on(RoomEvent.Disconnected, onDisconnected)
        .on(RoomEvent.ParticipantConnected, onParticipantConnected)
        .on(RoomEvent.ParticipantDisconnected, onParticipantDisconnected)
        .on(RoomEvent.TrackSubscribed, onTrackSubscribed)
        .on(RoomEvent.TrackUnsubscribed, onTrackUnsubscribed)
        .on(RoomEvent.TrackPublished, onTrackPublished)
        .on(RoomEvent.TrackUnpublished, onTrackUnpublished)
        .on(RoomEvent.LocalTrackPublished, onLocalTrackPublished)
        .on(RoomEvent.LocalTrackUnpublished, onLocalTrackUnpublished)
        .on(RoomEvent.DataReceived, onDataReceived);

    // 4. Connect
    try {
        await room.connect(data.livekitUrl, data.livekitToken);
    } catch (e) {
        alert(i18nT('error.connectRoom') + ' ' + e.message);
        leaveCall();
        return;
    }

    setSecurityBar(true);

    // 5. Publish tracks we already obtained in lobby
    if (preStream) {
        for (const track of preStream.getVideoTracks()) {
            try {
                const wantEnabled = lobbyState.camEnabled;
                track.enabled = wantEnabled;
                await room.localParticipant.publishTrack(track, {
                    source: Track.Source.Camera,
                    simulcast: true,
                    videoEncoding: {
                        maxBitrate: 1_500_000,
                        maxFramerate: 30
                    },
                    degradationPreference: 'maintain-resolution'
                });
                track.enabled = wantEnabled;
            } catch (e) { console.warn('publish video failed', e); }
        }
        for (const track of preStream.getAudioTracks()) {
            try {
                const wantEnabled = lobbyState.micEnabled;
                track.enabled = wantEnabled;
                await room.localParticipant.publishTrack(track, {
                    source: Track.Source.Microphone,
                    dtx: true,
                    red: true
                });
                track.enabled = wantEnabled;
            } catch (e) { console.warn('publish audio failed', e); }
        }

        // Двойная страховка через LiveKit API
        try {
            if (!lobbyState.camEnabled) {
                await room.localParticipant.setCameraEnabled(false);
            }
            if (!lobbyState.micEnabled) {
                await room.localParticipant.setMicrophoneEnabled(false);
            }
        } catch (e) { console.warn('state sync failed', e); }

        // Обновить кнопки в главном окне звонка
        const camOn = document.getElementById('cam-icon-on');
        const camOff = document.getElementById('cam-icon-off');
        const micOn = document.getElementById('mic-icon-on');
        const micOff = document.getElementById('mic-icon-off');
        if (camOn && camOff) {
            camOn.style.display = lobbyState.camEnabled ? '' : 'none';
            camOff.style.display = lobbyState.camEnabled ? 'none' : '';
        }
        if (micOn && micOff) {
            micOn.style.display = lobbyState.micEnabled ? '' : 'none';
            micOff.style.display = lobbyState.micEnabled ? 'none' : '';
        }
    }

    // 6. Attach local video + avatar
    const camPub = room.localParticipant.getTrackPublication(Track.Source.Camera);
    const localBox = document.getElementById('local-video-container');
    const localAv = document.getElementById('local-video-avatar');
    if (camPub && camPub.videoTrack) {
        camPub.videoTrack.attach(document.getElementById('local-video'));
        if (localAv) localAv.classList.remove('visible');
    } else {
        if (localAv) {
            console.log('[local-avatar-toggle]', { currentName: currentName, isGuest: isGuestName(currentName) });
            renderAvatarInto(localAv, currentName || '', isGuestName(currentName));
            localAv.classList.add('visible');
        }
    }
    // Подсветка для себя
    if (localBox) startSpeakerGlow(room.localParticipant, localBox);

    // 7. Attach already-present remote participants
    room.remoteParticipants.forEach(p => attachParticipant(p));
}

// ---------------------------------------------------------------------
// room event handlers
// ---------------------------------------------------------------------
function onConnected() {
    console.log('LiveKit: connected as', room.localParticipant.identity);
}

function onDisconnected(reason) {
    console.log('LiveKit: disconnected, reason =', reason);
    leaveCallUI();
    if (reason === DisconnectReason.CLIENT_INITIATED) {
        showRatingModal();
    } else {
        showToast(i18nT('error.disconnected'));
    }
}

function onParticipantConnected(participant) {
    console.log('Participant joined:', participant.identity, 'name:', participant.name);
    attachParticipant(participant);
}

function onParticipantDisconnected(participant) {
    console.log('Participant left:', participant.identity);
    detachParticipant(participant.identity);
}

function onTrackSubscribed(track, publication, participant) {
    console.log('Track subscribed:', participant.identity, track.kind, publication.source);
    attachParticipant(participant);
}

function onTrackUnsubscribed(track, publication, participant) {
    console.log('Track unsubscribed:', participant.identity, track.kind, publication.source);
    if (track.kind === 'video') {
        const panel = remotePanels.get(participant.identity);
        if (panel && panel.videoEl) panel.videoEl.srcObject = null;
    }
    attachParticipant(participant);
}

function onTrackPublished(publication, participant) {
    console.log('Track published:', participant.identity, publication.kind, publication.source);
    attachParticipant(participant);
}

function onTrackUnpublished(publication, participant) {
    console.log('Track unpublished:', participant.identity, publication.kind, publication.source);
    attachParticipant(participant);
}

function onLocalTrackUnpublished(publication) {
    if (publication.source === Track.Source.Camera) {
        const localAv = document.getElementById('local-video-avatar');
        if (localAv) {
            console.log('[local-unpub]', { currentName: currentName });
            renderAvatarInto(localAv, currentName || '', isGuestName(currentName));
            localAv.classList.add('visible');
        }
        const lv = document.getElementById('local-video');
        if (lv) lv.srcObject = null;
    }
}

function onLocalTrackPublished(publication) {
    if (publication.source === Track.Source.Camera && publication.videoTrack) {
        publication.videoTrack.attach(document.getElementById('local-video'));
        const localAv = document.getElementById('local-video-avatar');
        if (localAv) localAv.classList.remove('visible');
    }
}

function onDataReceived(payload, participant, kind, topic) {
    console.log('[chat] DataReceived:', {
        payloadSize: payload ? payload.byteLength : 0,
        from: participant ? participant.identity : '(self)',
        kind, topic
    });
    try {
        const text = new TextDecoder().decode(payload);
        console.log('[chat] decoded:', text);
        const msg = JSON.parse(text);
        if (msg.type === 'chat') {
            appendChatMessage(participant ? participant.identity : 'unknown', msg.text);
        } else {
            console.warn('[chat] not a chat message:', msg);
        }
    } catch (e) { console.warn('Bad datachannel payload:', e); }
}

// ---------------------------------------------------------------------
// video panel management
// ---------------------------------------------------------------------
// =====================================================================
// Universal fullscreen (iOS Safari + Android + desktop)
// =====================================================================
function isFullscreenActive() {
    return !!(document.fullscreenElement || document.webkitFullscreenElement);
}

function toggleFullscreen(wrapperOrVideo) {
    if (!wrapperOrVideo) return;
    if (isFullscreenActive()) { exitFullscreen(); return; }

    let video = wrapperOrVideo.tagName === 'VIDEO'
        ? wrapperOrVideo
        : wrapperOrVideo.querySelector('video');

    if (wrapperOrVideo.requestFullscreen) {
        wrapperOrVideo.requestFullscreen().catch(err => {
            console.warn('requestFullscreen failed, trying webkit', err);
            tryWebkitFullscreen(video, wrapperOrVideo);
        });
        return;
    }
    if (wrapperOrVideo.webkitRequestFullscreen) {
        wrapperOrVideo.webkitRequestFullscreen();
        return;
    }
    tryWebkitFullscreen(video, wrapperOrVideo);
}

function tryWebkitFullscreen(video, wrapper) {
    if (video && video.webkitEnterFullscreen) {
        try {
            attachFullscreenResume(video);
            video.webkitEnterFullscreen();
            return;
        } catch (e) { console.warn('webkitEnterFullscreen failed', e); }
    }
    if (wrapper && wrapper.webkitRequestFullscreen) {
        wrapper.webkitRequestFullscreen();
    }
}


// =====================================================================
// Fullscreen fix: восстановление play после exit fullscreen
// =====================================================================
function resumeAllVideos() {
    document.querySelectorAll('video').forEach(v => {
        if (v.srcObject && v.paused) {
            v.play().catch(e => console.warn('[fullscreen] resume play failed:', e));
        }
    });
}

document.addEventListener('fullscreenchange', () => {
    setTimeout(resumeAllVideos, 300);
});
document.addEventListener('webkitfullscreenchange', () => {
    setTimeout(resumeAllVideos, 300);
});

// iOS Safari native video fullscreen
function attachFullscreenResume(video) {
    if (!video) return;
    video.addEventListener('webkitendfullscreen', () => {
        setTimeout(() => {
            if (video.srcObject && video.paused) {
                video.play().catch(e => console.warn('[ios-fs] resume:', e));
            }
        }, 300);
    });
}

function exitFullscreen() {
    if (document.exitFullscreen)               document.exitFullscreen().catch(() => {});
    else if (document.webkitExitFullscreen)    document.webkitExitFullscreen();
    else if (document.webkitCancelFullScreen)  document.webkitCancelFullScreen();
}
function closeFullscreen() { exitFullscreen(); }

function attachDoubleTapFullscreen(el) {
    let lastTap = 0;
    el.addEventListener('touchend', (e) => {
        const now = Date.now();
        if (now - lastTap < 300) {
            e.preventDefault();
            toggleFullscreen(el);
        }
        lastTap = now;
    }, { passive: false });
}

// =====================================================================
// Avatar (camera off) + Active speaker glow
// =====================================================================
const AVATAR_GRADIENTS = [
    ['#8b5cf6', '#d946ef'],   // violet → fuchsia
    ['#6366f1', '#a855f7'],   // indigo → violet
    ['#a855f7', '#ec4899'],   // purple → pink
    ['#7c3aed', '#06b6d4'],   // violet → cyan
    ['#8b5cf6', '#f59e0b'],   // purple → amber
    ['#d946ef', '#3b82f6'],   // fuchsia → blue
    ['#10b981', '#06b6d4'],   // emerald → cyan
    ['#f43f5e', '#8b5cf6'],   // rose → violet
    ['#0ea5e9', '#6366f1'],   // sky → indigo
    ['#14b8a6', '#8b5cf6'],   // teal → violet
];
function hashString(s) {
    let h = 5381;
    for (let i = 0; i < s.length; i++) h = ((h << 5) + h) ^ s.charCodeAt(i);
    return Math.abs(h);
}
function avatarGradient(name) {
    const g = AVATAR_GRADIENTS[hashString(name || 'guest') % AVATAR_GRADIENTS.length];
    return 'linear-gradient(135deg, ' + g[0] + ' 0%, ' + g[1] + ' 100%)';
}
function guestSvg() {
    return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'
         + '<circle cx="12" cy="8" r="4"/><path d="M20 21a8 8 0 0 0-16 0"/></svg>';
}

function isGuestName(name) {
    if (name === undefined || name === null) return true;
    const t = String(name).trim();
    if (t === '') return true;
    const low = t.toLowerCase();
    if (low === 'гость' || low === 'guest' || low === 'гость ') return true;
    // Если первый символ не буква (цифра, знак) — тоже гость
    const first = t.charAt(0);
    if (!/[\p{L}]/u.test(first)) return true;
    return false;
}

function renderAvatarInto(container, name, forceGuest) {
    if (!container) return;
    const circle = container.querySelector('.avatar-circle');
    if (!circle) return;

    const guest = forceGuest || isGuestName(name);
    console.log('[avatar]', { name: name, forceGuest: forceGuest, isGuest: guest });

    if (guest) {
        circle.innerHTML = guestSvg();
        circle.style.background =
            'linear-gradient(135deg, #64748b 0%, #475569 60%, #334155 100%)';
    } else {
        const letter = String(name).trim().charAt(0).toUpperCase();
        while (circle.firstChild) circle.removeChild(circle.firstChild);
        circle.appendChild(document.createTextNode(letter));
        circle.style.background = avatarGradient(name);
    }
}

function ensureAvatarEl(wrapper, idSuffix) {
    let av = wrapper.querySelector('.video-avatar');
    if (!av) {
        av = document.createElement('div');
        av.className = 'video-avatar';
        av.innerHTML = '<div class="avatar-circle"></div>';
        // вставляем перед <video> чтобы был под ним в DOM, но выше по z-index
        wrapper.insertBefore(av, wrapper.firstChild);
    }
    return av;
}

function setAvatarVisible(wrapper, visible) {
    const av = wrapper.querySelector('.video-avatar');
    if (!av) return;
    av.classList.toggle('visible', visible);
}

// ---- Active speaker glow ----
const speakGlowTimers = new Map(); // identity -> raf id

function applyGlow(wrapper, level) {
    if (!wrapper) return;
    // level: 0..1
    const lv = Math.max(0, Math.min(1, level));
    wrapper.style.setProperty('--speak-glow', lv.toFixed(3));
    wrapper.classList.toggle('speaking', lv > 0.02);
}

function startSpeakerGlow(participant, wrapper) {
    stopSpeakerGlow(participant.identity);
    const loop = () => {
        const level = typeof participant.audioLevel === 'number' ? participant.audioLevel : 0;
        applyGlow(wrapper, level * 1.6); // усиливаем для заметности
        const id = speakGlowTimers.get(participant.identity);
        if (id !== false) {
            speakGlowTimers.set(participant.identity, requestAnimationFrame(loop));
        }
    };
    speakGlowTimers.set(participant.identity, requestAnimationFrame(loop));
}

function stopSpeakerGlow(identity) {
    const id = speakGlowTimers.get(identity);
    if (id) cancelAnimationFrame(id);
    speakGlowTimers.delete(identity);
}


// =====================================================================
// Dynamic grid layout
// =====================================================================
function updateGridLayout() {
    const grid = document.getElementById('remote-videos-grid');
    if (!grid) return;
    const total = remotePanels.size + remoteScreenPanels.size;
    if (total === 0) {
        grid.removeAttribute('data-count');
        grid.style.gridTemplateColumns = '';
        return;
    }

    // Для 1-2-3 — специальные раскладки через CSS
    if (total <= 3) {
        grid.dataset.count = String(total);
        grid.style.gridTemplateColumns = '';
        console.log('[grid] count=' + total + ' (smart layout)');
        return;
    }

    // Для 4+ — динамическая сетка
    grid.removeAttribute('data-count');
    const w = window.innerWidth;
    let cols;
    if (w < 600) {
        cols = total <= 4 ? 1 : 2;
    } else if (w < 900) {
        cols = total === 1 ? 1 : (total <= 4 ? 2 : 3);
    } else {
        if (total <= 4) cols = 2;
        else if (total <= 6) cols = 3;
        else if (total <= 9) cols = 3;
        else if (total <= 12) cols = 4;
        else if (total <= 16) cols = 4;
        else cols = 5;
    }
    grid.style.gridTemplateColumns = 'repeat(' + cols + ', minmax(0, 1fr))';
    console.log('[grid] count=' + total + ' cols=' + cols);
}

let __volResizeBound = false;
let __gridResizeTimer = null;
window.addEventListener('resize', () => {
    if (__gridResizeTimer) clearTimeout(__gridResizeTimer);
    __gridResizeTimer = setTimeout(updateGridLayout, 150);
});
if (!__volResizeBound) {
    __volResizeBound = true;
    window.addEventListener('resize', () => {
        document.querySelectorAll('.tile-volume-popup').forEach(popup => {
            const v = parseInt(popup.querySelector('input')?.value || '100', 10);
            updateSliderFill(popup, v);
        });
    });
}


// =====================================================================
// Per-participant volume control
// =====================================================================
function getVolumeFor(id) {
    try {
        const v = parseInt(localStorage.getItem('vidma-vol-' + id) || '100', 10);
        if (v >= 0 && v <= 100) return v;
    } catch (e) {}
    return 100;
}

function setVolumeFor(id, pct) {
    pct = Math.max(0, Math.min(200, parseInt(pct, 10)));
    if (isNaN(pct)) pct = 100;
    try { localStorage.setItem('vidma-vol-' + id, String(pct)); } catch (e) {}
    applyVolume(id, pct);

    const panel = remotePanels.get(id);
    if (!panel) return;
    const wrapper = panel.wrapperEl;
    const popup = wrapper.querySelector('.tile-volume-popup');
    if (!popup) return;
    const slider = popup.querySelector('input');
    const val = popup.querySelector('.tv-val');
    const btn = wrapper.querySelector('.tile-volume-btn');
    const icon = popup.querySelector('.tv-icon');
    if (slider && parseInt(slider.value, 10) !== pct) slider.value = String(pct);
    if (val) val.textContent = pct + '%';
    if (btn) btn.classList.toggle('muted', pct === 0);
    if (icon) updateVolumeIcon(icon, pct);
    updateSliderFill(popup, pct);
    popup.querySelectorAll('.tv-presets button').forEach(b => {
        b.classList.toggle('active', parseInt(b.dataset.v, 10) === pct);
    });
}

function updateSliderFill(popup, pct) {
    const slider = popup.querySelector('input');
    const fill = popup.querySelector('.tv-slider-fill');
    if (!slider || !fill) return;
    const W = slider.offsetWidth;
    const thumbW = 22;
    if (W > 0) {
        // Точная позиция: от центра thumb на 0% до центра thumb на 200%
        const fillPx = (pct / 200) * (W - thumbW) + thumbW / 2;
        fill.style.width = Math.round(fillPx) + 'px';
    } else {
        fill.style.width = (pct / 2) + '%';
    }
}



// =====================================================================
// Per-participant volume (Web Audio GainNode, 0-200%)
// =====================================================================
let __volCtx = null;
const __volNodes = new Map(); // identity -> { source, gain, mst }

function getVolCtx() {
    if (!__volCtx) {
        __volCtx = new (window.AudioContext || window.webkitAudioContext)();
    }
    if (__volCtx.state === 'suspended') __volCtx.resume().catch(() => {});
    return __volCtx;
}

function getVolumeFor(id) {
    try {
        const v = parseInt(localStorage.getItem('vidma-vol-' + id) || '100', 10);
        if (v >= 0 && v <= 200) return v;
    } catch (e) {}
    return 100;
}

function attachVolume(id, mediaStreamTrack) {
    if (!mediaStreamTrack) return;
    try {
        // Если уже есть — не дублируем
        if (__volNodes.has(id)) return;
        const ctx = getVolCtx();
        const stream = new MediaStream([mediaStreamTrack]);
        const source = ctx.createMediaStreamSource(stream);
        const gain = ctx.createGain();
        const pct = getVolumeFor(id);
        gain.gain.value = pct / 100;
        source.connect(gain);
        gain.connect(ctx.destination);
        __volNodes.set(id, { source, gain, mst: mediaStreamTrack });
        console.log('[volume] chain for', id.slice(0,6), 'gain =', (pct/100).toFixed(2));
        const resume = () => { ctx.resume().catch(()=>{}); document.removeEventListener('click', resume); };
        if (ctx.state === 'suspended') document.addEventListener('click', resume);
    } catch (e) {
        console.warn('[volume] WebAudio failed:', e);
    }
}

function detachVolume(id) {
    const n = __volNodes.get(id);
    if (!n) return;
    try { n.source.disconnect(); } catch (e) {}
    try { n.gain.disconnect(); } catch (e) {}
    __volNodes.delete(id);
    console.log('[volume] chain removed for', id.slice(0,6));
}

function applyVolume(id, pct) {
    pct = Math.max(0, Math.min(200, pct));
    const gainValue = pct / 100;
    const n = __volNodes.get(id);
    if (n) n.gain.gain.value = gainValue;
    console.log('[volume]', id.slice(0,6), '=', pct + '%', 'gain=' + gainValue.toFixed(2));
}

function setVolumeFor(id, pct) {
    pct = Math.max(0, Math.min(200, parseInt(pct, 10)));
    if (isNaN(pct)) pct = 100;
    try { localStorage.setItem('vidma-vol-' + id, String(pct)); } catch (e) {}
    applyVolume(id, pct);

    const panel = remotePanels.get(id);
    if (!panel) return;
    const slider = panel.wrapperEl.querySelector('.tv-slider-row input');
    const val = panel.wrapperEl.querySelector('.tv-val');
    const btn = panel.wrapperEl.querySelector('.tile-volume-btn');
    const icon = panel.wrapperEl.querySelector('.tv-icon');
    if (slider) {
        slider.value = String(pct);
        slider.style.setProperty('--vol-fill', (pct / 2) + '%');
    }
    if (val) val.textContent = pct + '%';
    if (btn) btn.classList.toggle('muted', pct === 0);
    if (icon) updateVolumeIcon(icon, pct);
    // Обновляем активные пресеты
    panel.wrapperEl.querySelectorAll('.tv-presets button').forEach(b => {
        b.classList.toggle('active', parseInt(b.dataset.v, 10) === pct);
    });
}

function updateVolumeIcon(el, pct) {
    let svg;
    if (pct === 0) {
        svg = '<svg viewBox="0 0 24 24"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/><line x1="23" y1="9" x2="17" y2="15"/><line x1="17" y1="9" x2="23" y2="15"/></svg>';
    } else if (pct < 50) {
        svg = '<svg viewBox="0 0 24 24"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/></svg>';
    } else if (pct < 150) {
        svg = '<svg viewBox="0 0 24 24"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/><path d="M15.54 8.46a5 5 0 0 1 0 7.07"/></svg>';
    } else {
        svg = '<svg viewBox="0 0 24 24"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/><path d="M15.54 8.46a5 5 0 0 1 0 7.07"/><path d="M19.07 4.93a10 10 0 0 1 0 14.14"/></svg>';
    }
    el.innerHTML = svg;
}

function toggleMuteFor(id) {
    const current = getVolumeFor(id);
    if (current === 0) {
        // Возврат к 100
        setVolumeFor(id, 100);
    } else {
        setVolumeFor(id, 0);
    }
}

function toggleVolumePopup(event, id) {
    event.stopPropagation();
    const panel = remotePanels.get(id);
    if (!panel) return;
    const wrapper = panel.wrapperEl;
    const isOpen = wrapper.classList.toggle('volume-open');
    if (isOpen) {
        // Закрываем все остальные попапы
        document.querySelectorAll('.remote-video-wrapper.volume-open').forEach(el => {
            if (el.id !== 'remote-' + id) el.classList.remove('volume-open');
        });
    }
}

function createVolumeControl(wrapper, id) {
    if (wrapper.querySelector('.tile-volume-btn')) return;
    const pct = getVolumeFor(id);
    const name = (wrapper.querySelector('.video-label')?.textContent || 'Гость').slice(0, 24);

    const btn = document.createElement('button');
    btn.className = 'tile-volume-btn' + (pct === 0 ? ' muted' : '');
    btn.title = (typeof i18nT === 'function') ? i18nT('volume.label') : 'Громкость';
    btn.innerHTML = '<svg viewBox="0 0 24 24"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/><path d="M15.54 8.46a5 5 0 0 1 0 7.07"/><path d="M19.07 4.93a10 10 0 0 1 0 14.14"/></svg>';
    btn.onclick = (e) => { e.stopPropagation(); toggleVolumePopup(e, id); };

    const popup = document.createElement('div');
    popup.className = 'tile-volume-popup';
    popup.innerHTML = `
        <div class="tv-header">
            <span class="tv-name">${name}</span>
            <span class="tv-val">${pct}%</span>
        </div>
        <div class="tv-slider-row">
            <span class="tv-icon" title="Mute">
                <svg viewBox="0 0 24 24"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/><path d="M15.54 8.46a5 5 0 0 1 0 7.07"/></svg>
            </span>
            <div class="tv-slider-wrapper">
                <div class="tv-slider-track"><div class="tv-slider-fill"></div></div>
                <input type="range" min="0" max="200" step="5" value="${pct}">
            </div>
        </div>
        <div class="tv-presets">
            <button data-v="0">Mute</button>
            <button data-v="50">50%</button>
            <button data-v="100">100%</button>
            <button data-v="150">150%</button>
            <button data-v="200">200%</button>
        </div>
    `;
    popup.addEventListener('click', (e) => e.stopPropagation());
    popup.addEventListener('mousedown', (e) => e.stopPropagation());
    popup.addEventListener('touchstart', (e) => e.stopPropagation());

    const slider = popup.querySelector('input');
    slider.addEventListener('input', (e) => {
        e.stopPropagation();
        setVolumeFor(id, e.target.value);
    });
    slider.addEventListener('change', (e) => {
        e.stopPropagation();
        setVolumeFor(id, e.target.value);
    });

    popup.querySelector('.tv-icon').addEventListener('click', () => toggleMuteFor(id));
    popup.querySelectorAll('.tv-presets button').forEach(b => {
        b.addEventListener('click', () => setVolumeFor(id, parseInt(b.dataset.v, 10)));
    });

    wrapper.appendChild(btn);
    wrapper.appendChild(popup);

    // Первичная инициализация fill
    const icon = popup.querySelector('.tv-icon');
    updateVolumeIcon(icon, pct);
    popup.querySelectorAll('.tv-presets button').forEach(b => {
        if (parseInt(b.dataset.v, 10) === pct) b.classList.add('active');
    });
    // Задержка — ждём пока popup появится в DOM и получит ширину
    setTimeout(() => updateSliderFill(popup, pct), 50);
}




// Закрытие попапа при клике вне
document.addEventListener('click', (e) => {
    if (!e.target.closest('.tile-volume-popup') && !e.target.closest('.tile-volume-btn')) {
        document.querySelectorAll('.remote-video-wrapper.volume-open').forEach(el => {
            el.classList.remove('volume-open');
        });
    }
});

window.setVolumeFor = setVolumeFor;
window.getVolumeFor = getVolumeFor;

function attachParticipant(participant) {
    const id = participant.identity;
    const displayName = participant.name || id.slice(0, 6);

    // ============ CAMERA TILE ============
    let camPanel = remotePanels.get(id);
    if (!camPanel) {
        const wrapper = document.createElement('div');
        wrapper.id = 'remote-' + id;
        wrapper.className = 'remote-video-wrapper camera-tile';

        const video = document.createElement('video');
        video.autoplay = true;
        video.playsInline = true;

        const lbl = document.createElement('div');
        lbl.className = 'video-label';
        lbl.textContent = displayName;

        const fsBtn = document.createElement('button');
        fsBtn.className = 'fullscreen-btn';
        fsBtn.title = 'Fullscreen';
        fsBtn.innerHTML = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"/></svg>';
        fsBtn.onclick = (e) => { e.stopPropagation(); toggleFullscreen(wrapper); };

        const av = document.createElement('div');
        av.className = 'video-avatar';
        av.innerHTML = '<div class="avatar-circle"></div>';
        renderAvatarInto(av, participant.name || '', isGuestName(participant.name));

        wrapper.appendChild(av);
        wrapper.appendChild(video);
        wrapper.appendChild(lbl);
        wrapper.appendChild(fsBtn);
        createVolumeControl(wrapper, id);
        attachDoubleTapFullscreen(wrapper);
        document.getElementById('remote-videos-grid').appendChild(wrapper);

        camPanel = { wrapperEl: wrapper, videoEl: video, labelEl: lbl, stream: new MediaStream(), name: participant.name || '' };
        remotePanels.set(id, camPanel);
        startSpeakerGlow(participant, wrapper);
    }

    // ============ SCREEN TILE ============
    let hasScreenShare = false;
    let hasCamera = false;
    participant.trackPublications.forEach(pub => {
        if (pub.isSubscribed && pub.track) {
            if (pub.kind === 'video' && pub.source === Track.Source.ScreenShare) hasScreenShare = true;
            if (pub.kind === 'video' && pub.source === Track.Source.Camera) hasCamera = true;
        }
    });

    let screenPanel = remoteScreenPanels.get(id);
    if (hasScreenShare && !screenPanel) {
        const wrapper = document.createElement('div');
        wrapper.id = 'remote-screen-' + id;
        wrapper.className = 'remote-video-wrapper screen-tile';
        wrapper.style.order = '-1';

        const video = document.createElement('video');
        video.autoplay = true;
        video.playsInline = true;

        const lbl = document.createElement('div');
        lbl.className = 'video-label';
        lbl.textContent = '\uD83D\uDCFA ' + i18nT('call.screen') + ' \u2014 ' + displayName;

        const fsBtn = document.createElement('button');
        fsBtn.className = 'fullscreen-btn';
        fsBtn.title = 'Fullscreen';
        fsBtn.innerHTML = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"/></svg>';
        fsBtn.onclick = (e) => { e.stopPropagation(); toggleFullscreen(wrapper); };

        wrapper.appendChild(video);
        wrapper.appendChild(lbl);
        wrapper.appendChild(fsBtn);
        attachDoubleTapFullscreen(wrapper);
        document.getElementById('remote-videos-grid').appendChild(wrapper);

        screenPanel = { wrapperEl: wrapper, videoEl: video, labelEl: lbl };
        remoteScreenPanels.set(id, screenPanel);
        console.log('[screen-tile] created for', id);
    } else if (!hasScreenShare && screenPanel) {
        try { screenPanel.wrapperEl.remove(); } catch (e) {}
        remoteScreenPanels.delete(id);
        screenPanel = null;
        console.log('[screen-tile] removed for', id);
    }

    // ============ ATTACH TRACKS ============
    participant.trackPublications.forEach(pub => {
        if (!pub.isSubscribed || !pub.track) return;
        if (pub.kind === 'audio') {
            // Аудио идёт через Web Audio, НЕ через video элемент
            try { attachVolume(id, pub.track.mediaStreamTrack); } catch (e) { console.warn(e); }
            return;
        }
        if (pub.kind === 'video' && pub.source === Track.Source.ScreenShare && screenPanel) {
            pub.track.attach(screenPanel.videoEl);
            return;
        }
        if (pub.kind === 'video' && pub.source === Track.Source.Camera) {
            pub.track.attach(camPanel.videoEl);
        }
    });

    // Avatar виден только если камеры нет
    setAvatarVisible(camPanel.wrapperEl, !hasCamera);

    if (participant.name && participant.name.trim()) camPanel.name = participant.name;
    const nameForAvatar = camPanel.name || participant.name || '';
    const av = camPanel.wrapperEl.querySelector('.video-avatar');
    if (av) renderAvatarInto(av, nameForAvatar, isGuestName(nameForAvatar));

    updateGridLayout();
}

function detachParticipant(identity) {
    detachVolume(identity);
    const camPanel = remotePanels.get(identity);
    if (camPanel) {
        stopSpeakerGlow(identity);
        try { camPanel.videoEl.srcObject = null; camPanel.wrapperEl.remove(); } catch (e) {}
        remotePanels.delete(identity);
    }
    const screenPanel = remoteScreenPanels.get(identity);
    if (screenPanel) {
        try { screenPanel.videoEl.srcObject = null; screenPanel.wrapperEl.remove(); } catch (e) {}
        remoteScreenPanels.delete(identity);
    }
    updateGridLayout();
}

function leaveCall() {
    if (room) {
        try { room.disconnect(); } catch (e) {}
        room = null;
    }
    leaveCallUI();
    showRatingModal();
}

function leaveCallUI() {
    // Stop all speaker glow loops
    speakGlowTimers.forEach(id => cancelAnimationFrame(id));
    speakGlowTimers.clear();
    // stop local preview
    const localVideo = document.getElementById('local-video');
    if (localVideo) localVideo.srcObject = null;

    // remove all remote panels
    remotePanels.forEach(p => { try { p.wrapperEl.remove(); } catch (e) {} });
    remotePanels.clear();
    remoteScreenPanels.forEach(p => { try { p.wrapperEl.remove(); } catch (e) {} });
    remoteScreenPanels.clear();

    setSecurityBar(false);
    document.getElementById('call-screen').style.display = 'none';
    { const __b = document.getElementById('toggle-bars-btn'); if (__b) { __b.classList.remove('visible'); __b.style.display = 'none'; } }
    document.getElementById('main-screen').style.display = 'block';
}


// =====================================================================
// Sprint 3 — Chat via LiveKit DataChannel (E2EE, no server storage)
// =====================================================================
const CHAT_TOPIC = 'vidma-chat';
let chatOpen = false;
let chatUnread = 0;
const chatHistory = new Map(); // roomId -> [{sender, text, ts, mine}]

function chatStorageKey(roomId) { return 'vidma-chat-' + roomId; }

function loadChatHistory(roomId) {
    if (!roomId) return [];
    if (chatHistory.has(roomId)) return chatHistory.get(roomId);
    try {
        const raw = localStorage.getItem(chatStorageKey(roomId));
        const arr = raw ? JSON.parse(raw) : [];
        chatHistory.set(roomId, arr);
        return arr;
    } catch (e) {
        chatHistory.set(roomId, []);
        return [];
    }
}

function saveChatHistory(roomId, msgs) {
    if (!roomId) return;
    chatHistory.set(roomId, msgs);
    try { localStorage.setItem(chatStorageKey(roomId), JSON.stringify(msgs)); }
    catch (e) { console.warn('chat save failed', e); }
}

function formatChatTime(ts) {
    const d = new Date(ts || Date.now());
    const hh = String(d.getHours()).padStart(2, '0');
    const mm = String(d.getMinutes()).padStart(2, '0');
    return hh + ':' + mm;
}

function renderChatMessage(msg) {
    const box = document.getElementById('chat-messages');
    if (!box) return;
    const empty = document.getElementById('chat-empty');
    if (empty) empty.remove();

    const el = document.createElement('div');
    el.className = 'chat-msg ' + (msg.system ? 'system' : (msg.mine ? 'mine' : 'theirs'));
    if (!msg.system) {
        const a = document.createElement('span');
        a.className = 'chat-author';
        a.textContent = msg.mine ? i18nT('call.you') : (msg.sender || i18nT('chat.participant'));
        el.appendChild(a);
    }
    const textNode = document.createTextNode(msg.text);
    el.appendChild(textNode);
    if (!msg.system) {
        const t = document.createElement('span');
        t.className = 'chat-time';
        t.textContent = formatChatTime(msg.ts);
        el.appendChild(t);
    }
    box.appendChild(el);
    box.scrollTop = box.scrollHeight;
}

function renderChatHistory(roomId) {
    const box = document.getElementById('chat-messages');
    if (!box) return;
    box.innerHTML = '';
    const msgs = loadChatHistory(roomId);
    if (msgs.length === 0) {
        const e = document.createElement('div');
        e.id = 'chat-empty';
        e.textContent = i18nT('chat.empty');
        box.appendChild(e);
        return;
    }
    msgs.forEach(renderChatMessage);
}

function appendChatMessage(from, text) {
    // from === currentSessionId → mine; else theirs
    const isMine = (from === currentSessionId);
    const msg = {
        sender: isMine ? null : (room?.remoteParticipants?.get?.(from)?.name || from),
        text: String(text).slice(0, 500),
        ts: Date.now(),
        mine: isMine
    };
    const arr = loadChatHistory(currentRoomId);
    arr.push(msg);
    if (arr.length > 500) arr.splice(0, arr.length - 500);
    saveChatHistory(currentRoomId, arr);

    renderChatMessage(msg);

    if (!chatOpen && !isMine) {
        chatUnread++;
        updateChatBadge();
        playChatPing();
        showToast(i18nT('chat.newMessage'));
    }
}

let __chatAudioCtx = null;
function playChatPing() {
    try {
        if (!__chatAudioCtx) {
            __chatAudioCtx = new (window.AudioContext || window.webkitAudioContext)();
        }
        const ctx = __chatAudioCtx;
        if (ctx.state === 'suspended') ctx.resume();
        const t0 = ctx.currentTime;
        // Мягкий "блип" из двух коротких тонов
        const osc = ctx.createOscillator();
        const gain = ctx.createGain();
        osc.type = 'sine';
        osc.frequency.setValueAtTime(880, t0);
        osc.frequency.setValueAtTime(1175, t0 + 0.08);
        gain.gain.setValueAtTime(0.0001, t0);
        gain.gain.exponentialRampToValueAtTime(0.15, t0 + 0.015);
        gain.gain.exponentialRampToValueAtTime(0.0001, t0 + 0.22);
        osc.connect(gain).connect(ctx.destination);
        osc.start(t0);
        osc.stop(t0 + 0.25);
    } catch (e) { /* тихо игнорируем */ }
}

function updateChatBadge() {
    const badge = document.getElementById('chat-badge');
    const btn = document.getElementById('toggle-chat');
    if (!badge || !btn) return;
    if (chatUnread > 0) {
        badge.textContent = chatUnread > 99 ? '99+' : String(chatUnread);
        btn.classList.add('has-unread');
    } else {
        badge.textContent = '0';
        btn.classList.remove('has-unread');
    }
}

function toggleChatPanel() {
    chatOpen = !chatOpen;
    const panel = document.getElementById('chat-panel');
    if (panel) panel.classList.toggle('open', chatOpen);
    if (chatOpen) {
        chatUnread = 0;
        updateChatBadge();
        renderChatHistory(currentRoomId);
        setTimeout(() => document.getElementById('chat-input')?.focus(), 50);
    }
}

function handleChatSubmit(ev) {
    ev.preventDefault();
    const input = document.getElementById('chat-input');
    if (!input) return;
    const text = input.value.trim();
    if (!text) return;
    sendChatMessage(text).then(() => {
        input.value = '';
    }).catch(e => {
        console.warn('send failed', e);
        showToast(i18nT('error.sendMessage'));
    });
}

async function sendChatMessage(text) {
    if (!room || !text) { console.warn('[chat] sendChatMessage: no room or text'); return; }
    if (!room.localParticipant || !room.localParticipant.publishData) {
        console.warn('[chat] publishData not available'); return;
    }
    const payload = new TextEncoder().encode(JSON.stringify({
        type: 'chat', text: String(text).slice(0, 500)
    }));
    console.log('[chat] publishData: size=', payload.byteLength, 'topic=', CHAT_TOPIC);
    try {
        await room.localParticipant.publishData(payload, {
            reliable: true,
            topic: CHAT_TOPIC
        });
        console.log('[chat] publishData: OK');
    } catch (e) {
        console.error('[chat] publishData FAILED:', e);
        showToast(i18nT('error.sendMessage'));
        throw e;
    }
    appendChatMessage(currentSessionId, text);
}

function showRatingModal() {
    const modal = document.getElementById('rating-modal');
    if (!modal) return;
    modal.classList.add('active');
    const stars = document.querySelectorAll('#stars span');
    stars.forEach(star => {
        star.onclick = () => {
            selectedRating = parseInt(star.dataset.value, 10);
            stars.forEach(s => s.classList.remove('active'));
            for (let i = 0; i < selectedRating; i++) stars[i].classList.add('active');
        };
    });
}

function closeRating() {
    const modal = document.getElementById('rating-modal');
    if (modal) modal.classList.remove('active');
    selectedRating = 0;
    const stars = document.querySelectorAll('#stars span');
    stars.forEach(s => s.classList.remove('active'));
}

function submitRating() {
    const commentEl = document.getElementById('rating-comment');
    const comment = commentEl ? commentEl.value.trim().slice(0, 500) : '';
    const rating = selectedRating;

    // Отправляем если есть хоть что-то (оценка или комментарий)
    if (rating > 0 || comment.length > 0) {
        fetch('/api/feedback', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                roomId: currentRoomId || 'unknown',
                rating: rating,
                comment: comment,
                userAgent: (navigator.userAgent || '').slice(0, 200)
            })
        }).then(r => r.json())
          .then(d => console.log('[feedback] sent:', d))
          .catch(e => console.warn('[feedback] failed:', e));
    }

    if (commentEl) commentEl.value = '';
    closeRating();
}

// ---------------------------------------------------------------------
// camera-permission retry from modal
// ---------------------------------------------------------------------
async function retryCamera() {
    const modal = document.getElementById('camera-choice-modal');
    if (modal) modal.classList.remove('active');
    if (!room) return;
    try {
        await room.localParticipant.enableCameraAndMicrophone();
    } catch (e) {
        if (modal) modal.classList.add('active');
    }
}

async function joinWithoutCamera() {
    const modal = document.getElementById('camera-choice-modal');
    if (modal) modal.classList.remove('active');
    if (!room) return;
    try {
        await room.localParticipant.setMicrophoneEnabled(true);
        await room.localParticipant.setCameraEnabled(false);
    } catch (e) { console.warn(e); }
}

// ---------------------------------------------------------------------
// URL ?room= auto-fill
// ---------------------------------------------------------------------
document.addEventListener('DOMContentLoaded', async () => {
    await i18nLoad();
    maybeShowCookieBanner();
    // Разбудить AudioContext при первом клике — политика браузера
    const resumeAudio = () => {
        try {
            if (!__chatAudioCtx) {
                __chatAudioCtx = new (window.AudioContext || window.webkitAudioContext)();
            }
            if (__chatAudioCtx.state === 'suspended') __chatAudioCtx.resume();
        } catch (e) {}
        document.removeEventListener('click', resumeAudio);
        document.removeEventListener('touchstart', resumeAudio);
    };
    document.addEventListener('click', resumeAudio);
    document.addEventListener('touchstart', resumeAudio);

    const inp = document.getElementById('room-id');
    if (!inp) return;

    inp.addEventListener('input', (e) => {
        const itype = e.inputType || '';
        if (itype.startsWith('delete')) return;
        const digits = e.target.value.replace(/\D/g, '').slice(0, 9);
        let fmt = digits;
        if (digits.length >= 7)      fmt = digits.slice(0,3)+'-'+digits.slice(3,6)+'-'+digits.slice(6);
        else if (digits.length === 6) fmt = digits.slice(0,3)+'-'+digits.slice(3,6)+'-';
        else if (digits.length >= 4) fmt = digits.slice(0,3)+'-'+digits.slice(3);
        else if (digits.length === 3) fmt = digits+'-';
        e.target.value = fmt;
        e.target.setSelectionRange(fmt.length, fmt.length);
    });

    const urlRoom = new URLSearchParams(location.search).get('room');
    if (urlRoom) {
        const digits = urlRoom.replace(/\D/g, '').slice(0, 9);
        let fmt = digits;
        if (digits.length >= 7)      fmt = digits.slice(0,3)+'-'+digits.slice(3,6)+'-'+digits.slice(6);
        else if (digits.length === 6) fmt = digits.slice(0,3)+'-'+digits.slice(3,6)+'-';
        else if (digits.length >= 4) fmt = digits.slice(0,3)+'-'+digits.slice(3);
        else if (digits.length === 3) fmt = digits+'-';

        // Проверяем что комната существует, потом открываем лобби
        if (digits.length === 9) {
            fetch('/api/room/' + fmt + '/exists')
                .then(r => r.json())
                .then(d => {
                    if (d && d.exists) {
                        const savedName = localStorage.getItem('vidma-name') || '';
                        console.log('[auto-lobby] room exists, opening lobby for', fmt, 'savedName=', savedName);
                        showLobby(fmt, savedName || '');
                    } else {
                        inp.value = fmt;
                    }
                })
                .catch(() => { inp.value = fmt; });
        } else {
            inp.value = fmt;
        }
    }
});

// expose to inline onclick handlers in HTML
window.createRoom = createRoom;
window.copyRoomLink = copyRoomLink;
window.joinCreatedRoom = joinCreatedRoom;
window.joinRoom = joinRoom;
window.showLobby = showLobby;
window.lobbyToggleMic = lobbyToggleMic;
window.lobbyToggleCam = lobbyToggleCam;
window.cancelLobby = cancelLobby;
window.confirmLobbyEntry = confirmLobbyEntry;
// =====================================================================
// Media controls (mic / cam / screen share)
// =====================================================================
async function toggleMic() {
    if (!room) return;
    const wasEnabled = room.localParticipant.isMicrophoneEnabled;
    try {
        await room.localParticipant.setMicrophoneEnabled(!wasEnabled);
        const micOn = document.getElementById('mic-icon-on');
        const micOff = document.getElementById('mic-icon-off');
        if (micOn) micOn.style.display = wasEnabled ? 'none' : '';
        if (micOff) micOff.style.display = wasEnabled ? '' : 'none';
        const btn = document.getElementById('toggle-mic');
        if (btn) btn.classList.toggle('off', wasEnabled);
        console.log('[toggleMic]', { was: wasEnabled, now: !wasEnabled });
    } catch (e) {
        console.warn('toggleMic failed', e);
    }
}

async function toggleCam() {
    if (!room) return;
    const wasEnabled = room.localParticipant.isCameraEnabled;
    try {
        await room.localParticipant.setCameraEnabled(!wasEnabled);

        if (!wasEnabled) {
            // При включении — переприкрепить локальное превью (SDK создал свежий трек)
            await new Promise(r => setTimeout(r, 200));
            const pub = room.localParticipant.getTrackPublication(Track.Source.Camera);
            const lv = document.getElementById('local-video');
            if (pub && pub.videoTrack && lv) pub.videoTrack.attach(lv);
        }

        const camOn = document.getElementById('cam-icon-on');
        const camOff = document.getElementById('cam-icon-off');
        if (camOn) camOn.style.display = wasEnabled ? 'none' : '';
        if (camOff) camOff.style.display = wasEnabled ? '' : 'none';

        // Локальный аватар — показать при выключенной камере
        const localAv = document.getElementById('local-video-avatar');
        if (localAv) {
            if (wasEnabled) {
                renderAvatarInto(localAv, currentName || '', isGuestName(currentName));
                localAv.classList.add('visible');
            } else {
                localAv.classList.remove('visible');
            }
        }
        const btn = document.getElementById('toggle-cam');
        if (btn) btn.classList.toggle('off', wasEnabled);
        console.log('[toggleCam]', { was: wasEnabled, now: !wasEnabled });
    } catch (e) {
        console.warn('toggleCam failed', e);
    }
}

async function toggleScreenShare() {
    if (!room) return;
    const currently = room.localParticipant.isScreenShareEnabled;
    const btn = document.getElementById('toggle-screen');
    try {
        await room.localParticipant.setScreenShareEnabled(!currently, {
            videoEncoding: { maxBitrate: 2_500_000, maxFramerate: 30 },
            audio: true
        });
        if (btn) btn.classList.toggle('active', !currently);
        console.log('[toggleScreenShare]', { was: currently, now: !currently });
    } catch (e) {
        console.warn('Screen share failed:', e);
        alert('Не удалось начать трансляцию: ' + e.message);
    }
}

window.toggleMic = toggleMic;
window.toggleCam = toggleCam;
window.toggleScreenShare = toggleScreenShare;
window.leaveCall = leaveCall;
window.submitRating = submitRating;
window.closeRating = closeRating;
window.retryCamera = retryCamera;
window.joinWithoutCamera = joinWithoutCamera;
window.shareRoomFromCall = copyRoomLink;
window.i18nSetLang = i18nSetLang;
window.i18nT = i18nT;
window.toggleChatPanel = toggleChatPanel;
window.handleChatSubmit = handleChatSubmit;
)js";

#endif // VIDMA_JS_H
